<cfscript>
local.faqItems = local.isEs ? [
  {q:"¿Funciona en todas las redes sociales?",a:"Los estilos usan caracteres Unicode y suelen funcionar en las redes principales. La apariencia puede variar según el dispositivo, el navegador o la plataforma."},
  {q:"¿Mi texto se envía a algún servidor?",a:"No. La conversión se realiza localmente en tu navegador."}
] : [
  {q:"Does it work on every social network?",a:"The styles use Unicode characters and generally work on the major networks. Their appearance can vary by device, browser, or platform."},
  {q:"Is my text sent to a server?",a:"No. Conversion happens locally in your browser."}
];
</cfscript>
<cfoutput><script type="application/ld+json">#serializeJSON({"@context":"https://schema.org","@type":"FAQPage","mainEntity":local.faqItems.map(function(item){return {"@type":"Question","name":item.q,"acceptedAnswer":{"@type":"Answer","text":item.a}};})})#</script><section class="tool-guide-docs"><div class="privacy-badge"><i class="fas fa-user-shield"></i><cfif local.isEs>Tu texto nunca sale de tu navegador.<cfelse>Your text never leaves your browser.</cfif></div><h2><i class="fas fa-info-circle"></i><cfif local.isEs>Cómo usar el generador<cfelse>How to use the generator</cfif></h2><h3><cfif local.isEs>Elegí un estilo y copialo<cfelse>Choose a style and copy it</cfif></h3><p><cfif local.isEs>Escribí o pegá tu texto, revisá las variantes y copiá la que mejor se adapte a tu post, bio, caption o comentario.<cfelse>Write or paste your text, review the variants, and copy the one that best fits your post, bio, caption, or comment.</cfif></p><h3><cfif local.isEs>Usalo con moderación<cfelse>Use it sparingly</cfif></h3><p><cfif local.isEs>Los estilos Unicode ayudan a destacar una idea corta. Para textos largos, el formato normal conserva mejor la lectura y la accesibilidad.<cfelse>Unicode styles help a short idea stand out. For longer text, normal formatting preserves readability and accessibility.</cfif></p><h3><cfif local.isEs>Preguntas frecuentes<cfelse>Frequently asked questions</cfif></h3><div class="faq-grid"><cfloop array="#local.faqItems#" index="local.fontFaq"><div class="faq-card"><h4>#local.fontFaq.q#</h4><p>#local.fontFaq.a#</p></div></cfloop></div></section></cfoutput>
