<cfscript>
local.faqItems = local.isEs ? [
  {q: "¿Qué versión de UUID genera?", a: "Genera UUID versión 4, es decir, identificadores completamente aleatorios (no basados en timestamp ni en dirección MAC), usando crypto.getRandomValues del navegador para asegurar aleatoriedad criptográficamente segura."},
  {q: "¿Pueden generarse dos UUID iguales por casualidad?", a: "Es estadísticamente despreciable: un UUID v4 tiene 2^122 combinaciones posibles, por lo que la probabilidad de colisión es prácticamente nula incluso generando miles de millones de IDs."},
  {q: "¿Cuál es la diferencia entre UUID y GUID?", a: "Son el mismo concepto (un identificador único de 128 bits) con nombres distintos: UUID es el término usado en la mayoría de los lenguajes y estándares, mientras que GUID es el nombre que le da Microsoft en su ecosistema (.NET, Windows)."}
] : [
  {q: "Which UUID version does it generate?", a: "It generates UUID version 4, meaning fully random identifiers (not based on a timestamp or MAC address), using the browser's crypto.getRandomValues to ensure cryptographically secure randomness."},
  {q: "Can two identical UUIDs be generated by chance?", a: "It's statistically negligible: a v4 UUID has 2^122 possible combinations, so the collision probability is effectively zero even when generating billions of IDs."},
  {q: "What's the difference between UUID and GUID?", a: "They're the same concept (a 128-bit unique identifier) with different names: UUID is the term used across most languages and standards, while GUID is the name Microsoft uses in its ecosystem (.NET, Windows)."}
];
</cfscript>
<cfoutput>
<script type="application/ld+json">
#serializeJSON({
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": local.faqItems.map(function(item) {
    return {"@type": "Question", "name": item.q, "acceptedAnswer": {"@type": "Answer", "text": item.a}};
  })
})#
</script>
<section class="tool-guide-docs">
  <div class="privacy-badge">
    <i class="fas fa-user-shield"></i>
    <cfif local.isEs>
      Generación 100% local con crypto.randomUUID: nada se envía a ningún servidor.
    <cfelse>
      100% local generation using crypto.randomUUID: nothing is sent to any server.
    </cfif>
  </div>

  <h2>
    <i class="fas fa-info-circle"></i>
    <cfif local.isEs>Guía Completa y Preguntas Frecuentes<cfelse>Complete Guide &amp; FAQ</cfif>
  </h2>

  <h3><cfif local.isEs>¿Qué es el Generador de UUID / GUID?<cfelse>What is the UUID / GUID Generator?</cfif></h3>
  <p>
    <cfif local.isEs>
      Genera identificadores únicos universales (UUID v4) al instante, uno por uno o en lote, para usar como claves primarias, IDs de sesión, nombres de archivo únicos o cualquier caso donde necesites un identificador prácticamente irrepetible.
    <cfelse>
      It generates universally unique identifiers (UUID v4) instantly, one at a time or in batches, for use as primary keys, session IDs, unique filenames, or any case where you need a practically non-repeating identifier.
    </cfif>
  </p>

  <h3><cfif local.isEs>Qué hace<cfelse>What it does</cfif></h3>
  <ul>
    <li><cfif local.isEs><strong>Generación en lote:</strong> de 1 a 20 UUID por vez.<cfelse><strong>Batch generation:</strong> 1 to 20 UUIDs at a time.</cfif></li>
    <li><cfif local.isEs><strong>Aleatoriedad criptográficamente segura:</strong> usa la API nativa crypto.randomUUID, con respaldo compatible en navegadores más antiguos.<cfelse><strong>Cryptographically secure randomness:</strong> uses the native crypto.randomUUID API, with a compatible fallback for older browsers.</cfif></li>
    <li><cfif local.isEs><strong>Copiar todo de una vez:</strong> los resultados se listan uno por línea, listos para copiar.<cfelse><strong>Copy all at once:</strong> results are listed one per line, ready to copy.</cfif></li>
  </ul>

  <h3><cfif local.isEs>Preguntas Frecuentes (FAQ)<cfelse>Frequently Asked Questions (FAQ)</cfif></h3>
  <div class="faq-grid">
    <cfloop array="#local.faqItems#" index="local.uuidFaq">
      <div class="faq-card">
        <h4>#local.uuidFaq.q#</h4>
        <p>#local.uuidFaq.a#</p>
      </div>
    </cfloop>
  </div>
</section>
</cfoutput>
