<main class="cf-development-page">
  <section id="top" class="cf-hero wow fadeIn" data-wow-duration="1s" data-wow-delay="0.2s"><div class="container"><div class="row"><div class="col-lg-7 wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.45s">
    <span class="hero-kicker">ColdFusion &middot; Lucee &middot; CFML</span>
    <h1>Desarrollo, <em>Soporte y Modernización ColdFusion</em></h1>
    <p class="cf-subtitle">Mantené tus aplicaciones CFML confiables hoy y preparadas para lo que sigue.</p>
    <p class="cf-lede">Ayudo a empresas a mantener, modernizar y ampliar aplicaciones de Adobe ColdFusion y Lucee, sin interrumpir los sistemas de los que dependen todos los días.</p>
    <div class="hero-cta-row scroll-to-section"><a href="https://wa.me/5492236026142?text=Hola%20Flavio%2C%20me%20gustar%C3%ADa%20hablar%20sobre%20mi%20proyecto%20ColdFusion" target="_blank" rel="noopener" class="hero-cta hero-cta-primary"><i class="fab fa-whatsapp"></i> Hablemos de tu proyecto ColdFusion</a><a href="#services" class="hero-cta hero-cta-secondary"><i class="fas fa-arrow-down"></i> Explorar servicios</a></div>
  </div><div class="col-lg-5 wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.65s"><div class="cf-hero-visual"><div class="cf-hero-visual-header"><span>Ecosistema ColdFusion</span><span class="cf-hero-visual-status">Operativo</span></div><aside class="cf-hero-panel" aria-label="Enfoque del proyecto ColdFusion"><span class="cf-hero-panel-label">Un socio práctico</span><h2>Claridad para la próxima decisión técnica.</h2><ul class="cf-hero-panel-list"><li><i class="fas fa-check-circle" aria-hidden="true"></i> Aplicaciones existentes</li><li><i class="fas fa-check-circle" aria-hidden="true"></i> Adobe ColdFusion y Lucee</li><li><i class="fas fa-check-circle" aria-hidden="true"></i> Rendimiento, APIs y bases de datos</li></ul></aside>

  <div id="tools" class="cf-development-tools wow fadeInUp" data-wow-duration="1s"><div class="container">
    <div class="cf-section-heading"><span class="hero-kicker">Herramientas para CFML</span><h2>Herramientas útiles para desarrollo, datos, CFML y servidores.</h2><p>Explorá las herramientas gratuitas que construí para el trabajo práctico alrededor de aplicaciones ColdFusion y su infraestructura.</p></div>
    <cfscript>
      local.cfToolCategories = ["desarrollo-datos", "cfml-servidores"];
      local.cfToolLabels = {};
      for (local.cfCat in request.toolCategories) local.cfToolLabels[local.cfCat.slug] = local.cfCat.labelEs;
      local.cfToolCount = 0;
      for (local.cfCountSlug in request.toolOrder) if (request.toolsRegistry[local.cfCountSlug].built and arrayFind(local.cfToolCategories, request.toolsRegistry[local.cfCountSlug].category)) local.cfToolCount++;
      local.cfToolNumber = 0;
    </cfscript>
    <div id="cf-tools-marquee" class="hero-tools-marquee cf-tools-marquee" aria-label="Herramientas de desarrollo y servidores CFML"><div class="hero-tools-marquee-header"><div class="hero-tools-marquee-title"><span><i class="fas fa-toolbox"></i> Herramientas seleccionadas</span><a href="/es/tools" class="hero-tools-all-link">Ver todas <i class="fas fa-arrow-right"></i></a></div><div class="hero-tools-marquee-meta"><small><i class="fas fa-pause"></i> Pausa al pasar</small></div></div><div class="hero-tools-marquee-viewport" tabindex="0"><div class="hero-tools-marquee-track"><div class="hero-tools-marquee-list"><cfset local.cfLastCategory = ""><cfoutput><cfloop array="#request.toolOrder#" index="local.cfSlug"><cfset local.cfTool = request.toolsRegistry[local.cfSlug]><cfif local.cfTool.built and arrayFind(local.cfToolCategories, local.cfTool.category)><cfif local.cfTool.category neq local.cfLastCategory><div class="hero-tools-category"><span>#local.cfToolLabels[local.cfTool.category]#</span></div><cfset local.cfLastCategory = local.cfTool.category></cfif><cfset local.cfToolNumber = local.cfToolNumber + 1><a href="/es/tools/#local.cfSlug#" data-tool-tooltip="#encodeForHTMLAttribute(local.cfTool.descEs)#" aria-label="#encodeForHTMLAttribute(local.cfTool.titleEs)#. #encodeForHTMLAttribute(local.cfTool.descEs)#"><span class="hero-tool-sequence">#numberFormat(local.cfToolNumber, '00')#</span><i class="#local.cfTool.iconPrefix# #local.cfTool.icon#"></i><span>#local.cfTool.titleEs#</span><i class="fas fa-arrow-right"></i></a></cfif></cfloop></cfoutput></div><div class="hero-tools-marquee-list" aria-hidden="true"><cfset local.cfLastCategoryRepeat = ""><cfoutput><cfloop array="#request.toolOrder#" index="local.cfSlugRepeat"><cfset local.cfToolRepeat = request.toolsRegistry[local.cfSlugRepeat]><cfif local.cfToolRepeat.built and arrayFind(local.cfToolCategories, local.cfToolRepeat.category)><cfif local.cfToolRepeat.category neq local.cfLastCategoryRepeat><div class="hero-tools-category"><span>#local.cfToolLabels[local.cfToolRepeat.category]#</span></div><cfset local.cfLastCategoryRepeat = local.cfToolRepeat.category></cfif><a href="/es/tools/#local.cfSlugRepeat#" tabindex="-1" data-tool-tooltip="#encodeForHTMLAttribute(local.cfToolRepeat.descEs)#"><span class="hero-tool-sequence"></span><i class="#local.cfToolRepeat.iconPrefix# #local.cfToolRepeat.icon#"></i><span>#local.cfToolRepeat.titleEs#</span><i class="fas fa-arrow-right"></i></a></cfif></cfloop></cfoutput></div></div></div></div>
  </div></div></div></div></div></div></section>

  <nav class="section-rail" aria-label="Navegación de sección"><ul class="section-rail-list">
    <li><a href="#top" class="section-rail-link" data-rail-target="top" data-section-label="Resumen" aria-label="Ir a Resumen"><span class="section-rail-label">Resumen</span></a></li>
    <li><a href="#expertise" class="section-rail-link" data-rail-target="expertise" data-section-label="Experiencia" aria-label="Ir a Experiencia"><span class="section-rail-label">Experiencia</span></a></li>
    <li><a href="#tools" class="section-rail-link" data-rail-target="tools" data-section-label="Herramientas" aria-label="Ir a Herramientas"><span class="section-rail-label">Herramientas</span></a></li>
    <li><a href="#services" class="section-rail-link" data-rail-target="services" data-section-label="Servicios" aria-label="Ir a Servicios"><span class="section-rail-label">Servicios</span></a></li>
    <li><a href="#approach" class="section-rail-link" data-rail-target="approach" data-section-label="Cómo trabajo" aria-label="Ir a Cómo trabajo"><span class="section-rail-label">Cómo trabajo</span></a></li>
    <li><a href="#faq" class="section-rail-link" data-rail-target="faq" data-section-label="Preguntas frecuentes" aria-label="Ir a Preguntas frecuentes"><span class="section-rail-label">Preguntas frecuentes</span></a></li>
    <li><a href="#contact" class="section-rail-link" data-rail-target="contact" data-section-label="Contacto" aria-label="Ir a Contacto"><span class="section-rail-label">Contacto</span></a></li>
  </ul></nav>

  <section id="expertise" class="cf-section wow fadeInUp" data-wow-duration="1s"><div class="container cf-expertise-copy"><span class="hero-kicker">Experiencia ColdFusion confiable</span><h2>Conservá tus sistemas valiosos y confiables.</h2><p>Las aplicaciones heredadas son sistemas de negocio valiosos, no software descartable. El trabajo correcto mejora la estabilidad, reduce riesgos concretos y permite que tu equipo tenga claridad sobre los próximos pasos. Me enfoco en mejoras útiles, entregas cuidadosas y comunicación clara.</p></div></section>

  <section id="services" class="cf-section is-soft wow fadeInUp" data-wow-duration="1s"><div class="container"><div class="cf-section-heading"><span class="hero-kicker">Servicios</span><h2>Ayuda concreta para cada etapa de tu aplicación CFML.</h2><p>Desde un problema puntual hasta una colaboración técnica continua, trabajo sobre la aplicación y la infraestructura que ya tenés.</p></div><div class="row g-4">
    <div class="col-md-6 col-lg-4"><article id="legacy-support" class="cf-service-card"><i class="fas fa-life-ring" aria-hidden="true"></i><h3>Soporte para ColdFusion y Lucee heredados</h3><p>Mantenimiento, diagnóstico, mejoras y estabilización de aplicaciones CFML existentes.</p></article></div>
    <div class="col-md-6 col-lg-4"><article id="upgrades-migration" class="cf-service-card"><i class="fas fa-sync-alt" aria-hidden="true"></i><h3>Actualizaciones y migraciones ColdFusion</h3><p>Planificación y ejecución de actualizaciones a versiones soportadas de Adobe ColdFusion o Lucee, con mínima interrupción.</p></article></div>
    <div class="col-md-6 col-lg-4"><article id="performance-security" class="cf-service-card"><i class="fas fa-shield-alt" aria-hidden="true"></i><h3>Optimización de rendimiento y seguridad</h3><p>Mejoras en consultas lentas, rendimiento, confiabilidad, calidad de código y postura de seguridad.</p></article></div>
    <div class="col-md-6 col-lg-4"><article id="api-modernization" class="cf-service-card"><i class="fas fa-plug" aria-hidden="true"></i><h3>Integraciones de APIs y modernización</h3><p>Conexión con APIs REST, proveedores de pago, CRMs, servicios cloud e interfaces JavaScript modernas.</p></article></div>
    <div class="col-md-6 col-lg-4"><article class="cf-service-card"><i class="fas fa-database" aria-hidden="true"></i><h3>Optimización de SQL Server y bases de datos</h3><p>Diagnóstico de cuellos de botella, optimización de consultas e índices y mayor confiabilidad de los datos.</p></article></div>
    <div class="col-md-6 col-lg-4"><article class="cf-service-card"><i class="fas fa-tools" aria-hidden="true"></i><h3>Soporte técnico continuo</h3><p>Mantenimiento confiable, resolución de incidentes y mejoras planificadas.</p></article></div>
    <div class="col-md-6 col-lg-4"><article id="hosting" class="cf-service-card cf-hosting-card"><i class="fas fa-server" aria-hidden="true"></i><h3>Hosting administrado multi-tecnología</h3><p>Alojá aplicaciones PHP y Adobe ColdFusion con SQL Server o MySQL, respaldadas por un panel de gestión práctico.</p></article></div>
    <div class="col-md-6 col-lg-4"><article class="cf-service-card cf-hosting-card"><i class="fas fa-sliders-h" aria-hidden="true"></i><h3>Panel y gestión del servicio</h3><p>Administrá dominios, SSL, bases de datos, backups, logs y los aspectos operativos que necesita tu aplicación.</p></article></div>
    <div class="col-md-6 col-lg-4"><article class="cf-service-card cf-hosting-card"><i class="fas fa-code" aria-hidden="true"></i><h3>Hosting para aplicaciones PHP y ColdFusion</h3><p>Publicá y operá aplicaciones de negocio desarrolladas con PHP o Adobe ColdFusion en un mismo entorno confiable.</p></article></div>
  </div></div></section>

  <section id="why-work-with-me" class="cf-section wow fadeInUp" data-wow-duration="1s"><div class="container"><div class="cf-section-heading"><span class="hero-kicker">Por qué trabajar conmigo</span><h2>Experiencia aplicada a lo que tus sistemas necesitan.</h2></div><div class="row justify-content-center"><div class="col-lg-9"><ul class="cf-reason-list">
    <li><i class="fas fa-check-circle" aria-hidden="true"></i><span>Más de 15 años de experiencia en desarrollo web</span></li><li><i class="fas fa-check-circle" aria-hidden="true"></i><span>Sólida experiencia en ColdFusion, Lucee, CFML y SQL Server</span></li><li><i class="fas fa-check-circle" aria-hidden="true"></i><span>Enfoque práctico para aplicaciones heredadas y críticas para el negocio</span></li><li><i class="fas fa-check-circle" aria-hidden="true"></i><span>Integraciones modernas, APIs, HTML5, JavaScript, Bootstrap y soluciones preparadas para cloud</span></li><li><i class="fas fa-check-circle" aria-hidden="true"></i><span>Comunicación clara y responsabilidad desde el diagnóstico hasta la entrega</span></li>
  </ul></div></div></div></section>

  <section id="approach" class="cf-section is-soft wow fadeInUp" data-wow-duration="1s"><div class="container"><div class="cf-section-heading"><span class="hero-kicker">Cómo trabajo</span><h2>Un camino claro del diagnóstico a la entrega.</h2></div><div class="row g-4">
    <div class="col-md-6 col-lg-3"><article class="cf-step-card"><span class="cf-step-number">1</span><h3>Entender</h3><p>Revisar la aplicación, la infraestructura, las necesidades del negocio y los riesgos actuales.</p></article></div><div class="col-md-6 col-lg-3"><article class="cf-step-card"><span class="cf-step-number">2</span><h3>Planificar</h3><p>Definir prioridades prácticas, alcance y un camino de implementación.</p></article></div><div class="col-md-6 col-lg-3"><article class="cf-step-card"><span class="cf-step-number">3</span><h3>Mejorar</h3><p>Entregar cambios enfocados con código limpio y mantenible.</p></article></div><div class="col-md-6 col-lg-3"><article class="cf-step-card"><span class="cf-step-number">4</span><h3>Acompañar</h3><p>Mantener la aplicación estable y hacerla evolucionar cuando sea necesario.</p></article></div>
  </div></div></section>

  <section id="faq" class="cf-section wow fadeInUp" data-wow-duration="1s"><div class="container"><div class="cf-section-heading"><span class="hero-kicker">Preguntas frecuentes</span><h2>Preguntas comunes sobre soporte ColdFusion.</h2></div><div class="cf-faq">
    <details><summary>¿Soportás aplicaciones ColdFusion heredadas?</summary><p>Sí. Mantengo, diagnostico, refactorizo y amplío aplicaciones Adobe ColdFusion existentes, incluso codebases antiguos.</p></details><details><summary>¿Trabajás con Lucee?</summary><p>Sí. Lucee Server y el soporte de aplicaciones CFML forman parte de mi experiencia principal.</p></details><details><summary>¿Podés actualizar una aplicación ColdFusion antigua?</summary><p>Sí. Puedo evaluar la aplicación, detectar riesgos de compatibilidad y planificar una actualización a una versión soportada de Adobe ColdFusion o Lucee.</p></details><details><summary>¿Podés mejorar una aplicación ColdFusion lenta?</summary><p>Sí. Puedo investigar el comportamiento de la aplicación, las consultas, la infraestructura y el código para identificar mejoras prácticas de rendimiento.</p></details><details><summary>¿Podés integrar una aplicación ColdFusion con APIs externas?</summary><p>Sí. Trabajo con APIs REST, proveedores de pago, CRMs, servicios cloud e interfaces JavaScript.</p></details><details><summary>¿Ofrecés soporte continuo?</summary><p>Sí. Se pueden coordinar mantenimiento, resolución de incidentes y mejoras planificadas según las necesidades de la aplicación.</p></details>
  </div></div></section>

  <section id="contact" class="cf-final-cta wow fadeInUp" data-wow-duration="1s"><div class="container"><h2>¿Necesitás un desarrollador ColdFusion experimentado para tu aplicación existente?</h2><p>Hablemos del próximo paso práctico para tu aplicación, ya sea soporte, modernización, mejoras de rendimiento o una nueva integración.</p><a href="https://wa.me/5492236026142?text=Hola%20Flavio%2C%20me%20gustar%C3%ADa%20hablar%20sobre%20mi%20aplicaci%C3%B3n%20ColdFusion" target="_blank" rel="noopener" class="hero-cta hero-cta-primary"><i class="fab fa-whatsapp"></i> Iniciar una conversación</a></div></section>
</main>
