<cfset local.isEs = session.lan eq "es">
<main class="cf-development-page">
  <section id="top" class="cf-hero wow fadeIn" data-wow-duration="1s" data-wow-delay="0.2s">
    <div class="container"><div class="row"><div class="col-lg-7 wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.45s">
      <span class="hero-kicker"><cfif local.isEs>SEO técnico · GEO · Datos estructurados<cfelse>Technical SEO · GEO · Structured data</cfif></span>
      <h1><cfif local.isEs>SEO técnico + GEO para que tu sitio sea <em>fácil de entender y encontrar.</em><cfelse>Technical SEO + GEO to make your site <em>easy to understand and find.</em></cfif></h1>
      <p class="cf-subtitle"><cfif local.isEs>Generative Engine Optimization para búsquedas con IA, basada en la arquitectura real de tu sitio.<cfelse>Generative Engine Optimization for AI search, based on your site's real architecture.</cfif></p>
      <p class="cf-lede"><cfif local.isEs>Reviso e implemento las señales que ayudan a Google, otros buscadores y asistentes de IA a rastrear, interpretar y presentar correctamente tus servicios, experiencia y contenido público.<cfelse>I audit and implement the signals that help Google, other search engines, and AI assistants crawl, interpret, and accurately present your public services, expertise, and content.</cfif></p>
      <div class="hero-cta-row"><a href="https://wa.me/5492236026142?text=<cfif local.isEs>Hola%20Flavio%2C%20quisiera%20consultar%20por%20una%20auditor%C3%ADa%20SEO%20t%C3%A9cnica%20y%20visibilidad%20para%20IA<cfelse>Hello%20Flavio%2C%20I%20would%20like%20to%20ask%20about%20a%20technical%20SEO%20and%20AI%20search%20visibility%20audit</cfif>" target="_blank" rel="noopener" class="hero-cta hero-cta-primary"><i class="fab fa-whatsapp"></i> <cfif local.isEs>Solicitar una auditoría<cfelse>Request an audit</cfif></a><a href="#scope" class="hero-cta hero-cta-secondary"><i class="fas fa-arrow-down"></i> <cfif local.isEs>Ver qué incluye<cfelse>See what is included</cfif></a></div>
    </div><div class="col-lg-5 wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.65s"><div class="cf-hero-visual"><div class="cf-hero-visual-header"><span><cfif local.isEs>Ecosistema SEO + GEO<cfelse>SEO + GEO ecosystem</cfif></span><span class="cf-hero-visual-status"><cfif local.isEs>Listo<cfelse>Ready</cfif></span></div>
      <div class="cf-development-tools"><div class="container">
        <cfscript>
          local.geoToolCategory = "marketing-seo-social";
          local.geoToolNumber = 0;
          local.geoToolsUrl = local.isEs ? "/es/tools" : "/tools";
        </cfscript>
        <div class="hero-tools-marquee cf-tools-marquee" aria-label="<cfif local.isEs>Herramientas SEO y GEO<cfelse>SEO and GEO tools</cfif>"><div class="hero-tools-marquee-header"><div class="hero-tools-marquee-title"><span><i class="fas fa-toolbox"></i> <cfif local.isEs>Herramientas seleccionadas<cfelse>Selected tools</cfif></span><a href="<cfoutput>#local.geoToolsUrl#</cfoutput>" class="hero-tools-all-link"><cfif local.isEs>Ver todas<cfelse>View all</cfif> <i class="fas fa-arrow-right"></i></a></div><div class="hero-tools-marquee-meta"><small><i class="fas fa-pause"></i> <cfif local.isEs>Pausa al pasar<cfelse>Hover to pause</cfif></small></div></div><div class="hero-tools-marquee-viewport" tabindex="0"><div class="hero-tools-marquee-track"><div class="hero-tools-marquee-list"><cfoutput><cfloop array="#request.toolOrder#" index="local.geoSlug"><cfset local.geoTool = request.toolsRegistry[local.geoSlug]><cfif local.geoTool.built and local.geoTool.category eq local.geoToolCategory><cfset local.geoToolNumber++><a href="#local.geoToolsUrl#/#local.geoSlug#" data-tool-tooltip="#encodeForHTMLAttribute(local.isEs ? local.geoTool.descEs : local.geoTool.descEn)#" aria-label="#encodeForHTMLAttribute(local.isEs ? local.geoTool.titleEs : local.geoTool.titleEn)#"><span class="hero-tool-sequence">#numberFormat(local.geoToolNumber, '00')#</span><i class="#local.geoTool.iconPrefix# #local.geoTool.icon#"></i><span>#local.isEs ? local.geoTool.titleEs : local.geoTool.titleEn#</span><i class="fas fa-arrow-right"></i></a></cfif></cfloop></cfoutput></div><div class="hero-tools-marquee-list" aria-hidden="true"><cfset local.geoToolNumberRepeat = 0><cfoutput><cfloop array="#request.toolOrder#" index="local.geoSlugRepeat"><cfset local.geoToolRepeat = request.toolsRegistry[local.geoSlugRepeat]><cfif local.geoToolRepeat.built and local.geoToolRepeat.category eq local.geoToolCategory><cfset local.geoToolNumberRepeat++><a href="#local.geoToolsUrl#/#local.geoSlugRepeat#" tabindex="-1" data-tool-tooltip="#encodeForHTMLAttribute(local.isEs ? local.geoToolRepeat.descEs : local.geoToolRepeat.descEn)#"><span class="hero-tool-sequence">#numberFormat(local.geoToolNumberRepeat, '00')#</span><i class="#local.geoToolRepeat.iconPrefix# #local.geoToolRepeat.icon#"></i><span>#local.isEs ? local.geoToolRepeat.titleEs : local.geoToolRepeat.titleEn#</span><i class="fas fa-arrow-right"></i></a></cfif></cfloop></cfoutput></div></div></div></div>
      </div></div>
      <aside class="cf-hero-panel" aria-label="<cfif local.isEs>Enfoque de la auditoría SEO y GEO<cfelse>SEO and GEO audit focus</cfif>"><span class="cf-hero-panel-label"><cfif local.isEs>Un plan concreto<cfelse>A practical plan</cfif></span><h2><cfif local.isEs>Claridad antes de invertir en contenido o campañas.<cfelse>Clarity before investing in content or campaigns.</cfif></h2><ul class="cf-hero-panel-list"><li><i class="fas fa-check-circle" aria-hidden="true"></i> <cfif local.isEs>SEO técnico y rastreo<cfelse>Technical SEO and crawling</cfif></li><li><i class="fas fa-check-circle" aria-hidden="true"></i> <cfif local.isEs>Datos estructurados y entidades<cfelse>Structured data and entities</cfif></li><li><i class="fas fa-check-circle" aria-hidden="true"></i> <cfif local.isEs>Contenido público entendible<cfelse>Understandable public content</cfif></li></ul></aside>
    </div></div></div>
  </section>

  <nav class="section-rail" data-rail-always-visible="true" aria-label="<cfif local.isEs>Navegación de sección<cfelse>Section navigation</cfif>"><ul class="section-rail-list">
    <li><a href="#top" class="section-rail-link" data-rail-target="top" data-section-label="<cfif local.isEs>Resumen<cfelse>Overview</cfif>" aria-label="<cfif local.isEs>Ir al resumen<cfelse>Go to overview</cfif>"><span class="section-rail-label"><cfif local.isEs>Resumen<cfelse>Overview</cfif></span></a></li>
    <li><a href="#problem" class="section-rail-link" data-rail-target="problem" data-section-label="<cfif local.isEs>El problema<cfelse>The problem</cfif>" aria-label="<cfif local.isEs>Ir al problema<cfelse>Go to the problem</cfif>"><span class="section-rail-label"><cfif local.isEs>El problema<cfelse>The problem</cfif></span></a></li>
    <li><a href="#scope" class="section-rail-link" data-rail-target="scope" data-section-label="<cfif local.isEs>Qué incluye<cfelse>What is included</cfif>" aria-label="<cfif local.isEs>Ir a qué incluye<cfelse>Go to what is included</cfif>"><span class="section-rail-label"><cfif local.isEs>Qué incluye<cfelse>What is included</cfif></span></a></li>
    <li><a href="#process" class="section-rail-link" data-rail-target="process" data-section-label="<cfif local.isEs>Cómo se trabaja<cfelse>How it works</cfif>" aria-label="<cfif local.isEs>Ir a cómo se trabaja<cfelse>Go to how it works</cfif>"><span class="section-rail-label"><cfif local.isEs>Cómo trabajo<cfelse>How it works</cfif></span></a></li>
    <li><a href="#fit" class="section-rail-link" data-rail-target="fit" data-section-label="<cfif local.isEs>Para quién<cfelse>Who it is for</cfif>" aria-label="<cfif local.isEs>Ir a para quién<cfelse>Go to who it is for</cfif>"><span class="section-rail-label"><cfif local.isEs>Para quién<cfelse>Who it is for</cfif></span></a></li>
    <li><a href="#faq" class="section-rail-link" data-rail-target="faq" data-section-label="FAQ" aria-label="<cfif local.isEs>Ir a preguntas frecuentes<cfelse>Go to frequently asked questions</cfif>"><span class="section-rail-label">FAQ</span></a></li>
    <li><a href="#contact" class="section-rail-link" data-rail-target="contact" data-section-label="<cfif local.isEs>Contacto<cfelse>Contact</cfif>" aria-label="<cfif local.isEs>Ir a contacto<cfelse>Go to contact</cfif>"><span class="section-rail-label"><cfif local.isEs>Contacto<cfelse>Contact</cfif></span></a></li>
  </ul></nav>

  <section id="problem" class="cf-section is-soft wow fadeInUp"><div class="container"><div class="cf-section-heading"><span class="hero-kicker"><cfif local.isEs>El problema<cfelse>The problem</cfif></span><h2><cfif local.isEs>Un sitio puede funcionar bien y seguir siendo difícil de interpretar.<cfelse>A site can work well and still be hard to interpret.</cfif></h2><p><cfif local.isEs>Cuando las URLs, el HTML, los metadatos y las relaciones entre páginas no son claros, el contenido importante puede quedar mal rastreado, duplicado o sin contexto. Las herramientas de IA tienen la misma limitación: necesitan información pública, factual y semántica antes de poder usarla con confianza.<cfelse>When URLs, HTML, metadata, and relationships between pages are unclear, important content can be poorly crawled, duplicated, or left without context. AI tools have the same limitation: they need public, factual, semantic information before they can use it reliably.</cfif></p></div></div></section>

  <section id="scope" class="cf-section wow fadeInUp"><div class="container"><div class="cf-section-heading"><span class="hero-kicker"><cfif local.isEs>Qué incluye<cfelse>What is included</cfif></span><h2><cfif local.isEs>Una auditoría útil, seguida de mejoras que se pueden mantener.<cfelse>A useful audit followed by improvements that can be maintained.</cfif></h2></div><div class="row g-4">
    <div class="col-md-6 col-lg-4"><article class="cf-service-card"><i class="fas fa-search" aria-hidden="true"></i><h3><cfif local.isEs>Rastreo e indexación<cfelse>Crawling and indexation</cfif></h3><p><cfif local.isEs>Revisión de URLs, redirecciones, canonicals, robots, sitemap, errores de cobertura y páginas que no deberían competir en los resultados.<cfelse>Review of URLs, redirects, canonicals, robots, sitemap, coverage issues, and pages that should not compete in results.</cfif></p></article></div>
    <div class="col-md-6 col-lg-4"><article class="cf-service-card"><i class="fas fa-code" aria-hidden="true"></i><h3><cfif local.isEs>HTML y metadatos<cfelse>HTML and metadata</cfif></h3><p><cfif local.isEs>Titles, descripciones, headings, enlaces internos, contenido server-side y Open Graph para que la información esencial no dependa de JavaScript o elementos visuales.<cfelse>Titles, descriptions, headings, internal links, server-side content, and Open Graph so essential information does not depend on JavaScript or visual elements.</cfif></p></article></div>
    <div class="col-md-6 col-lg-4"><article class="cf-service-card"><i class="fas fa-project-diagram" aria-hidden="true"></i><h3><cfif local.isEs>Entidades y Schema.org<cfelse>Entities and Schema.org</cfif></h3><p><cfif local.isEs>Datos estructurados que coinciden con contenido visible: organización, persona, servicios, software, FAQs, artículos, breadcrumbs o casos, cuando corresponda.<cfelse>Structured data that matches visible content: organization, person, services, software, FAQs, articles, breadcrumbs, or cases where appropriate.</cfif></p></article></div>
    <div class="col-md-6 col-lg-4"><article class="cf-service-card"><i class="fas fa-robot" aria-hidden="true"></i><h3><cfif local.isEs>GEO y visibilidad para IA<cfelse>GEO and AI search visibility</cfif></h3><p><cfif local.isEs>Generative Engine Optimization: claridad sobre qué ofrece la empresa, qué problemas resuelve y qué experiencia demuestra, sin texto artificial ni promesas de aparición en respuestas de terceros.<cfelse>Generative Engine Optimization: clarity about what the business offers, what it solves, and what experience it demonstrates—without artificial copy or promises of appearance in third-party answers.</cfif></p></article></div>
    <div class="col-md-6 col-lg-4"><article class="cf-service-card"><i class="fas fa-tachometer-alt" aria-hidden="true"></i><h3><cfif local.isEs>Rendimiento técnico<cfelse>Technical performance</cfif></h3><p><cfif local.isEs>Mejoras razonables de entrega, recursos y caché cuando afectan la experiencia, el rastreo o la interpretación de las páginas.<cfelse>Practical delivery, resource, and cache improvements when they affect user experience, crawling, or page interpretation.</cfif></p></article></div>
    <div class="col-md-6 col-lg-4"><article class="cf-service-card"><i class="fas fa-list-check" aria-hidden="true"></i><h3><cfif local.isEs>Plan e implementación<cfelse>Plan and implementation</cfif></h3><p><cfif local.isEs>Un plan priorizado puede quedar listo para tu equipo o convertirse en una implementación técnica sobre el sitio existente, sin reescrituras innecesarias.<cfelse>A prioritized plan can be handed to your team or turned into technical implementation on the existing site, without unnecessary rewrites.</cfif></p></article></div>
  </div></div></section>

  <section id="process" class="cf-section cf-geo-process wow fadeInUp"><div class="container"><div class="cf-section-heading"><span class="hero-kicker"><cfif local.isEs>Cómo se trabaja<cfelse>How it works</cfif></span><h2><cfif local.isEs>De la evidencia a las prioridades.<cfelse>From evidence to priorities.</cfif></h2></div><div class="row g-4"><div class="col-md-4"><article class="cf-step-card"><span class="cf-step-number">1</span><h3><cfif local.isEs>Auditar<cfelse>Audit</cfif></h3><p><cfif local.isEs>Entender la arquitectura, el contenido público y las señales técnicas actuales.<cfelse>Understand the architecture, public content, and current technical signals.</cfif></p></article></div><div class="col-md-4"><article class="cf-step-card"><span class="cf-step-number">2</span><h3><cfif local.isEs>Priorizar<cfelse>Prioritize</cfif></h3><p><cfif local.isEs>Separar quick wins, correcciones necesarias y mejoras de largo plazo.<cfelse>Separate quick wins, necessary corrections, and longer-term improvements.</cfif></p></article></div><div class="col-md-4"><article class="cf-step-card"><span class="cf-step-number">3</span><h3><cfif local.isEs>Implementar y validar<cfelse>Implement and validate</cfif></h3><p><cfif local.isEs>Aplicar cambios, comprobar HTML, metadatos y schemas, y documentar cómo mantenerlos.<cfelse>Apply changes, check HTML, metadata, and schemas, and document how to maintain them.</cfif></p></article></div></div></div></section>

  <section id="fit" class="cf-section wow fadeInUp"><div class="container"><div class="cf-section-heading"><span class="hero-kicker"><cfif local.isEs>Para quién<cfelse>Who it is for</cfif></span><h2><cfif local.isEs>Para sitios y aplicaciones existentes que necesitan claridad técnica.<cfelse>For existing sites and applications that need technical clarity.</cfif></h2><p><cfif local.isEs>El servicio se adapta a ColdFusion/CFML, Lucee, WordPress, PHP y otras arquitecturas. Es especialmente útil al renovar un sitio, publicar servicios nuevos, ordenar un portfolio, corregir problemas de indexación o preparar contenido técnico para audiencias y sistemas automatizados.<cfelse>The service adapts to ColdFusion/CFML, Lucee, WordPress, PHP, and other architectures. It is especially useful when refreshing a site, publishing new services, organizing a portfolio, fixing indexation problems, or preparing technical content for people and automated systems.</cfif></p></div></div></section>

  <section id="faq" class="cf-section is-soft wow fadeInUp"><div class="container"><div class="cf-section-heading"><span class="hero-kicker">FAQ</span><h2><cfif local.isEs>Preguntas frecuentes.<cfelse>Common questions.</cfif></h2></div><div class="cf-faq">
    <details><summary><cfif local.isEs>¿Qué incluye una auditoría?<cfelse>What does an audit include?</cfif></summary><p><cfif local.isEs>Revisión de rastreo, indexación, URLs, metadatos, datos estructurados, enlaces internos, contenido HTML y prioridades de implementación.<cfelse>A review of crawling, indexation, URLs, metadata, structured data, internal links, HTML content, and implementation priorities.</cfif></p></details>
    <details><summary><cfif local.isEs>¿Garantizás aparecer en ChatGPT o Google AI?<cfelse>Do you guarantee appearance in ChatGPT or Google AI?</cfif></summary><p><cfif local.isEs>No. Ningún proveedor puede garantizarlo. El trabajo mejora la claridad técnica y semántica del sitio, sin prometer resultados que dependen de plataformas externas.<cfelse>No. No provider can guarantee it. The work improves the technical and semantic clarity of the site without promising outcomes controlled by external platforms.</cfif></p></details>
    <details><summary><cfif local.isEs>¿Podés implementar los cambios?<cfelse>Can you implement the changes?</cfif></summary><p><cfif local.isEs>Sí. La auditoría puede entregarse como plan priorizado o convertirse en una implementación técnica acordada sobre el sitio actual.<cfelse>Yes. The audit can be delivered as a prioritized plan or turned into agreed technical implementation on the current site.</cfif></p></details>
  </div></div></section>

  <section id="contact" class="cf-final-cta wow fadeInUp"><div class="container"><h2><cfif local.isEs>¿Querés saber qué está frenando la visibilidad de tu sitio?<cfelse>Want to know what is holding back your site's visibility?</cfif></h2><p><cfif local.isEs>Contame qué sitio o aplicación querés revisar y cuál es el objetivo comercial o técnico.<cfelse>Tell me which site or application you want to review and the commercial or technical goal.</cfif></p><a href="https://wa.me/5492236026142?text=<cfif local.isEs>Hola%20Flavio%2C%20quisiera%20consultar%20por%20SEO%20t%C3%A9cnico%20y%20visibilidad%20para%20IA<cfelse>Hello%20Flavio%2C%20I%20would%20like%20to%20ask%20about%20technical%20SEO%20and%20AI%20search%20visibility</cfif>" target="_blank" rel="noopener" class="hero-cta hero-cta-primary"><i class="fab fa-whatsapp"></i> <cfif local.isEs>Iniciar una conversación<cfelse>Start a conversation</cfif></a></div></section>
</main>
