<cfprocessingdirective pageencoding="utf-8">
<style>
  .aip-app { --aip-ink:#10243e; --aip-muted:#68788e; --aip-line:#e5ebf2; --aip-bg:#f5f8fb; color:var(--aip-ink); }
  .aip-app .aip-shell { background:linear-gradient(135deg,#f7fbff 0%,#fff 55%); border:1px solid var(--aip-line); border-radius:24px; padding:clamp(18px,3vw,32px); box-shadow:0 16px 45px rgba(16,36,62,.08); }
  .aip-topline { display:flex; justify-content:space-between; align-items:flex-start; gap:16px; margin-bottom:24px; }
  .aip-kicker { color:#198754; font-size:.72rem; font-weight:800; letter-spacing:.13em; text-transform:uppercase; margin:0 0 6px; }
  .aip-topline h2 { font-size:clamp(1.45rem,3vw,2.1rem); margin:0; font-weight:800; }
  .aip-privacy { color:var(--aip-muted); font-size:.84rem; margin:8px 0 0; }
  .aip-privacy i { color:#198754; }
  .aip-nav { display:flex; flex-wrap:wrap; gap:8px; border-bottom:1px solid var(--aip-line); padding-bottom:18px; margin-bottom:22px; }
  .aip-nav button { border:0; background:transparent; border-radius:10px; padding:10px 14px; color:var(--aip-muted); font-weight:700; font-size:.9rem; }
  .aip-nav button.active { background:var(--aip-ink); color:#fff; }
  .aip-screen { display:none; }
  .aip-screen.active { display:block; }
  .aip-empty { padding:42px 18px; text-align:center; border:1px dashed #cbd6e2; border-radius:18px; background:#fff; }
  .aip-empty i { color:#198754; font-size:2rem; margin-bottom:12px; }
  .aip-empty h3 { font-size:1.25rem; }
  .aip-empty p { color:var(--aip-muted); max-width:480px; margin:0 auto 20px; }
  .aip-stat { background:#fff; border:1px solid var(--aip-line); border-radius:16px; padding:18px; height:100%; }
  .aip-stat small { color:var(--aip-muted); display:block; font-weight:700; }
  .aip-stat strong { display:block; font-size:1.55rem; margin-top:4px; }
  .aip-ai-card { background:#fff; border:1px solid var(--aip-line); border-radius:18px; padding:20px; height:100%; }
  .aip-card-head { display:flex; justify-content:space-between; gap:10px; align-items:flex-start; margin-bottom:18px; }
  .aip-ai-name { font-size:1.2rem; font-weight:800; margin:0; }
  .aip-ai-meta { color:var(--aip-muted); font-size:.83rem; margin:4px 0 0; }
  .aip-health { border-radius:999px; padding:5px 9px; font-size:.72rem; font-weight:800; white-space:nowrap; }
  .aip-health.good { color:#146c43; background:#d1e7dd; } .aip-health.warn { color:#997404; background:#fff3cd; } .aip-health.bad { color:#b02a37; background:#f8d7da; }
  .aip-limit { border-top:1px solid var(--aip-line); padding-top:14px; margin-top:14px; }
  .aip-limit-head { display:flex; justify-content:space-between; gap:10px; font-size:.86rem; margin-bottom:7px; }
  .aip-limit-head strong { font-size:.92rem; }
  .aip-progress { height:9px; background:#edf1f5; border-radius:99px; overflow:hidden; }
  .aip-progress-bar { height:100%; border-radius:99px; background:#198754; transition:width .25s ease; }
  .aip-progress-bar.warn { background:#f0ad00; } .aip-progress-bar.bad { background:#dc3545; }
  .aip-limit-details { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:8px; margin-top:10px; color:var(--aip-muted); font-size:.76rem; }
  .aip-limit-details span { display:block; } .aip-limit-details b { color:var(--aip-ink); display:block; font-size:.84rem; }
  .aip-table-wrap { overflow-x:auto; border:1px solid var(--aip-line); border-radius:16px; background:#fff; }
  .aip-table { min-width:650px; margin:0; } .aip-table th { color:var(--aip-muted); font-size:.74rem; text-transform:uppercase; letter-spacing:.05em; border-bottom:1px solid var(--aip-line); }
  .aip-table td { vertical-align:middle; } .aip-table input { min-width:100px; }
  .aip-compare-table { min-width:760px; margin:0; } .aip-compare-table th { color:var(--aip-muted); font-size:.74rem; text-transform:uppercase; letter-spacing:.05em; border-bottom:1px solid var(--aip-line); white-space:nowrap; } .aip-compare-table td { vertical-align:middle; }
  .aip-context { color:var(--aip-muted); font-size:.78rem; margin-top:8px; } .aip-context i { width:14px; color:#198754; }
  .aip-custom-name-wrap.is-hidden { display:none; }
  .aip-note { color:var(--aip-muted); font-size:.83rem; }
  .aip-list-item { display:flex; justify-content:space-between; align-items:center; gap:16px; border:1px solid var(--aip-line); background:#fff; border-radius:14px; padding:14px 16px; margin-bottom:10px; }
  .aip-list-actions { display:flex; gap:6px; flex-wrap:wrap; } .aip-list-actions button { white-space:nowrap; }
  .aip-form-section { background:var(--aip-bg); border-radius:16px; padding:16px; margin-bottom:16px; }
  .aip-form-section h4 { font-size:.95rem; font-weight:800; margin:0 0 14px; }
  .aip-limit-row { background:#fff; border:1px solid var(--aip-line); border-radius:12px; padding:14px; margin-bottom:10px; }
  .aip-limit-row .remove-limit { float:right; }
  .aip-footer { border-top:1px solid var(--aip-line); margin-top:24px; padding-top:16px; display:flex; justify-content:space-between; gap:12px; align-items:center; flex-wrap:wrap; }
  .aip-import-label { cursor:pointer; } .aip-app .btn-close{float:right;width:1.5em;height:1.5em;border:0;background:transparent;font-size:1.5rem;line-height:1;color:#000;opacity:.6;padding:0}.aip-app .btn-close:hover{opacity:1}.aip-app .btn-close .aip-close-mark{display:block;} @media(max-width:575px){ .aip-topline{display:block}.aip-topline .btn{margin-top:14px;width:100%}.aip-shell{border-radius:16px!important}.aip-nav button{flex:1 1 calc(50% - 8px)} .aip-list-item{display:block}.aip-list-actions{margin-top:12px} }
  .aip-app .modal{overflow-x:hidden!important;overflow-y:auto!important}.aip-app .modal-dialog{height:auto!important;max-height:none!important;margin:1rem auto}.aip-app .modal-content{height:auto!important;max-height:none!important;display:flex;flex-direction:column}.aip-app .modal-header,.aip-app .modal-footer{flex:0 0 auto}.aip-app .modal-body{flex:0 0 auto;min-height:0;max-height:none!important;overflow:visible!important}
</style>

<div class="aip-app" id="aiUsagePlanner">
  <div class="aip-shell">
    <div class="aip-topline">
      <div><p class="aip-kicker">AI planning workspace</p><h2>AI Usage Planner</h2><p class="aip-privacy"><i class="fas fa-lock"></i> Your data stays in this browser. No APIs, account, or database.</p></div>
    </div>
    <nav class="aip-nav" aria-label="AI Usage Planner screens">
      <button type="button" data-aip-screen="onboarding">Onboarding</button><button type="button" data-aip-screen="manage">Manage AIs</button><button type="button" data-aip-screen="dashboard">Dashboard</button><button type="button" data-aip-screen="compare">Compare</button><button type="button" data-aip-screen="update">Update Usage</button>
    </nav>

    <section class="aip-screen" data-aip-panel="onboarding"><div class="row align-items-center g-4"><div class="col-lg-7"><p class="aip-kicker">Start with the provider's numbers</p><h3 class="mb-3">See which AI has room left before you start working.</h3><p class="aip-note mb-4">For each AI, enter the percentage used exactly as shown by its provider and the next reset date. Add separate windows such as weekly and 5-hour usage. Usage is entered manually in this version.</p><button class="btn btn-dark" type="button" data-aip-action="add">Configure your first AI <i class="fas fa-arrow-right ms-1"></i></button></div><div class="col-lg-5"><div class="aip-stat"><small><i class="fas fa-compass me-1"></i> How it works</small><strong>Used % + reset</strong><p class="aip-note mb-0">Enter two simple values. The planner calculates what remains and which AI is safest to use.</p></div></div></div></section>

    <section class="aip-screen" data-aip-panel="manage"><div class="d-flex justify-content-between align-items-center mb-3"><div><h3 class="h4 mb-1">Manage AIs</h3><p class="aip-note mb-0">Configure names, limits, windows, and reset times.</p></div><button class="btn btn-outline-success" type="button" data-aip-action="add"><i class="fas fa-plus"></i> Add AI</button></div><div data-aip-list></div></section>

    <section class="aip-screen" data-aip-panel="dashboard"><div class="row g-3 mb-4" data-aip-stats></div><div class="row g-3" data-aip-cards></div></section>

    <section class="aip-screen" data-aip-panel="compare"><div class="mb-3"><h3 class="h4 mb-1">Compare AIs</h3><p class="aip-note mb-0">A side-by-side view using each AI's most restrictive active limit.</p></div><div data-aip-compare></div></section>

    <section class="aip-screen" data-aip-panel="update"><div class="mb-3"><h3 class="h4 mb-1">Quick Update Usage</h3><p class="aip-note mb-0">Enter the current total consumed for each limit. Values are saved on this device.</p></div><div data-aip-update></div></section>

    <div class="aip-footer"><span class="aip-note"><i class="fas fa-shield-alt"></i> Local-only storage · export a backup before clearing browser data.</span><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-secondary" type="button" data-aip-action="export"><i class="fas fa-download"></i> Export JSON</button><label class="btn btn-sm btn-outline-secondary aip-import-label mb-0"><i class="fas fa-upload"></i> Import JSON<input type="file" accept="application/json,.json" data-aip-import hidden></label></div></div>
  </div>

    <div class="modal fade" data-aip-modal tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><form data-aip-form><div class="modal-header"><h5 class="modal-title">Add AI</h5><button type="button" class="btn-close" data-bs-dismiss="modal" data-dismiss="modal" aria-label="Close"><span class="aip-close-mark" aria-hidden="true">&times;</span></button></div><div class="modal-body"><input type="hidden" name="aiId"><div class="aip-form-section"><h4>AI details</h4><div class="row g-3"><div class="col-md-6"><label class="form-label">Provider</label><select name="providerKey" class="form-select"><option value="custom">Custom / other</option><option value="codex">Codex</option><option value="claude-code">Claude Code</option><option value="gemini-models">Gemini Models</option><option value="gemini-other-models">Gemini Other Models</option></select></div><div class="col-md-6 aip-custom-name-wrap"><label class="form-label">Custom name <span class="text-danger">*</span></label><input name="name" class="form-control" placeholder="e.g. My local model"></div></div></div><div class="aip-form-section"><div class="d-flex justify-content-between align-items-center mb-3"><h4 class="mb-0">Usage limits</h4><button type="button" class="btn btn-sm btn-outline-success" data-aip-action="add-limit"><i class="fas fa-plus"></i> Add limit</button></div><div data-aip-limit-editor></div><p class="aip-note mb-0">Each limit has a provider window, usage percentage, and reset date.</p></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal" data-dismiss="modal">Cancel</button><button class="btn btn-success" type="submit">Save AI</button></div></form></div></div></div>
</div>

<script>
(function () {
  'use strict';
  var root = document.getElementById('aiUsagePlanner'); if (!root) return;
  var storageKey = 'coldfusionexpert.aiUsagePlanner.v1', state = loadState(), activeScreen = state.ais.length ? 'dashboard' : 'onboarding', modal = root.querySelector('[data-aip-modal]'), editingId = null;
  var providerSuggestions = [{key:'codex',label:'Codex'},{key:'claude-code',label:'Claude Code'},{key:'gemini-models',label:'Gemini Models'},{key:'gemini-other-models',label:'Gemini Other Models'},{key:'custom',label:'Custom / other'}];
  function uid(prefix){ return (prefix || 'id') + '-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2,8); }
  function windowLabel(hours){ hours=Number(hours); return hours===5?'Session (5 hours)':hours===24?'Daily (24 hours)':hours===168?'Weekly (7 days)':hours===720?'Monthly (30 days)':'Custom window'; }
  function defaultLimit(){ var reset = new Date(Date.now() + 7 * 86400000); return {id:uid('limit'),label:windowLabel(168),allowance:100,windowHours:168,used:0,usedPercent:0,resetAt:reset.toISOString(),updatedAt:new Date().toISOString()}; }
  function emptyState(){ return {version:1,ais:[]}; }
  function loadState(){ try { var parsed=JSON.parse(localStorage.getItem(storageKey)||''); return parsed && Array.isArray(parsed.ais) ? normalize(parsed) : emptyState(); } catch(e){ return emptyState(); } }
  function normalize(data){ data.ais.forEach(function(ai){ ai.id=ai.id||uid('ai'); ai.name=String(ai.name||'Unnamed AI'); ai.providerKey=ai.providerKey==='gemini'?'gemini-models':(ai.providerKey||'custom'); ai.limits=Array.isArray(ai.limits)?ai.limits:[]; ai.limits.forEach(function(l){ l.id=l.id||uid('limit'); l.label=String(l.label||'Usage limit'); l.unit=String(l.unit||'requests'); l.allowance=Math.max(0,Number(l.allowance)||0); l.windowHours=Math.max(.1,Number(l.windowHours)||168); l.used=Math.max(0,Number(l.used)||0); l.usedPercent=Math.max(0,Math.min(100,Number(l.usedPercent)!=null&&!isNaN(Number(l.usedPercent))?Number(l.usedPercent):(l.allowance?l.used/l.allowance*100:0))); var reset=new Date(l.resetAt); l.resetAt=isNaN(reset.getTime())?new Date(Date.now()+l.windowHours*3600000).toISOString():reset.toISOString(); }); }); return data; }
  function save(){ state=normalize(state); localStorage.setItem(storageKey,JSON.stringify(state)); render(); }
  function fmtNum(v){ return new Intl.NumberFormat(undefined,{maximumFractionDigits:1}).format(Math.max(0,v)); }
  function fmtDate(iso){ var d=new Date(iso); return isNaN(d)?'Unknown':d.toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}); }
  function hoursLeft(l){ return Math.max(0,(new Date(l.resetAt)-Date.now())/3600000); }
  function calc(l){ var usedPercent=Math.max(0,Math.min(100,providerFor().getUsage(null,l))), left=hoursLeft(l), pct=100-usedPercent, elapsed=Math.max(0,Math.min(l.windowHours,l.windowHours-left)), expected=100*(elapsed/l.windowHours), delta=usedPercent-expected, signal=usedPercent>100?'bad':delta>15?'bad':delta>5?'warn':'good'; return {left:left,pct:pct,usedPercent:usedPercent,expected:expected,actual:usedPercent,delta:delta,signal:signal,perHour:left?Math.max(0,pct/left):0,perDay:left?Math.max(0,pct/left*24):0}; }
  function providerFor(){ return new ManualUsageProvider(); }
  function UsageProvider(){ if(this.constructor===UsageProvider) throw new Error('UsageProvider is abstract'); }
  UsageProvider.prototype.getUsage=function(){ throw new Error('Implement getUsage'); };
  function ManualUsageProvider(){} ManualUsageProvider.prototype=Object.create(UsageProvider.prototype); ManualUsageProvider.prototype.constructor=ManualUsageProvider; ManualUsageProvider.prototype.getUsage=function(ai,limit){ return Number(limit.usedPercent)||0; };
  function providerName(key){ var match=providerSuggestions.find(function(p){return p.key===key;}); return match?match.label:'Custom / other'; }
  function aiDisplayName(ai){ return ai.providerKey==='custom'?ai.name:providerName(ai.providerKey); }
  function aiMeta(ai){ return ai.providerKey==='custom'?providerName(ai.providerKey):''; }
  function health(ai){ if(!ai.limits.length)return {signal:'warn',pct:0}; return ai.limits.map(calc).reduce(function(w,c){ return c.pct<w.pct||c.signal==='bad'&&w.signal!=='bad'?c:w; }); }
  function setScreen(name){ activeScreen=name; root.querySelectorAll('[data-aip-screen]').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-aip-screen')===name);}); root.querySelectorAll('[data-aip-panel]').forEach(function(p){p.classList.toggle('active',p.getAttribute('data-aip-panel')===name);}); render(); }
  function esc(s){ return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];}); }
  function bar(c){ return '<div class="aip-progress"><div class="aip-progress-bar '+c.signal+'" style="width:'+Math.max(0,Math.min(100,c.pct))+'%"></div></div>'; }
  function limitHtml(l){ var c=calc(l), expectedClass=c.delta>0?'text-danger':'text-success'; return '<div class="aip-limit"><div class="aip-limit-head"><strong>'+esc(windowLabel(l.windowHours))+'</strong><span>Used <b>'+fmtNum(c.usedPercent)+'%</b> · '+fmtNum(c.pct)+'% left</span></div>'+bar(c)+'<div class="aip-limit-details"><span>Used<b>'+fmtNum(c.usedPercent)+'%</b></span><span>Reset<b>'+ (c.left<24?fmtNum(c.left)+'h':fmtNum(c.left/24)+'d')+'</b></span><span>Safe pace<b>'+fmtNum(c.perHour)+'% / hour</b></span><span>Safe pace<b>'+fmtNum(c.perDay)+'% / day</b></span><span>Expected vs actual<b class="'+expectedClass+'">'+fmtNum(c.expected)+'% / '+fmtNum(c.usedPercent)+'%</b></span></div></div>'; }
  function render(){ root.querySelectorAll('[data-aip-screen]').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-aip-screen')===activeScreen);}); root.querySelectorAll('[data-aip-panel]').forEach(function(p){p.classList.toggle('active',p.getAttribute('data-aip-panel')===activeScreen);}); var list=root.querySelector('[data-aip-list]'), cards=root.querySelector('[data-aip-cards]'), stats=root.querySelector('[data-aip-stats]'), update=root.querySelector('[data-aip-update]');
    if(list) list.innerHTML=state.ais.length?state.ais.map(function(ai){return '<div class="aip-list-item"><div><strong>'+esc(aiDisplayName(ai))+'</strong><div class="aip-ai-meta">'+(aiMeta(ai)?esc(aiMeta(ai))+' · ':'')+ai.limits.length+' limit'+(ai.limits.length===1?'':'s')+'</div></div><div class="aip-list-actions"><button class="btn btn-sm btn-outline-secondary" data-aip-edit="'+ai.id+'">Edit</button><button class="btn btn-sm btn-outline-danger" data-aip-remove="'+ai.id+'" aria-label="Remove '+esc(aiDisplayName(ai))+'" title="Remove AI"><i class="fas fa-trash-alt" aria-hidden="true"></i></button></div></div>';}).join(''):'<div class="aip-empty"><i class="fas fa-layer-group"></i><h3>No AIs configured yet</h3><p>Add your first AI and its limits to unlock the dashboard.</p><button class="btn btn-success" data-aip-action="add">Add your first AI</button></div>';
    if(cards) cards.innerHTML=state.ais.length?state.ais.map(function(ai){var h=health(ai);return '<div class="col-xl-4 col-md-6"><article class="aip-ai-card"><div class="aip-card-head"><div><h3 class="aip-ai-name">'+esc(aiDisplayName(ai))+'</h3>'+(aiMeta(ai)?'<p class="aip-ai-meta">'+esc(aiMeta(ai))+'</p>':'')+'</div><span class="aip-health '+h.signal+'">'+(h.signal==='good'?'On track':h.signal==='warn'?'Watch pace':'Over pace')+'</span></div>'+ (ai.limits.length?ai.limits.map(limitHtml).join(''):'<p class="aip-note">No limits configured.</p>') +'<button class="btn btn-sm btn-light w-100 mt-3" data-aip-update-ai="'+ai.id+'"><i class="fas fa-pen"></i> Update usage</button></article></div>';}).join(''):'<div class="col-12"><div class="aip-empty"><i class="fas fa-chart-line"></i><h3>Your dashboard is ready when you are</h3><p>Configure an AI and its first limit to see safe pace, remaining percentage, and expected versus actual usage.</p><button class="btn btn-success" data-aip-action="add">Configure an AI</button></div></div>';
    if(stats) { var total=state.ais.reduce(function(n,a){return n+a.limits.length;},0), worst=state.ais.length?state.ais.map(health).reduce(function(a,b){return b.pct<a.pct?b:a;}):null; stats.innerHTML='<div class="col-sm-4"><div class="aip-stat"><small>AI tools</small><strong>'+state.ais.length+'</strong></div></div><div class="col-sm-4"><div class="aip-stat"><small>Active limits</small><strong>'+total+'</strong></div></div><div class="col-sm-4"><div class="aip-stat"><small>Most restrictive</small><strong>'+(worst?fmtNum(worst.pct)+'% left':'—')+'</strong></div></div>'; }
    if(update) update.innerHTML=state.ais.length?'<div class="aip-table-wrap"><table class="table aip-table"><thead><tr><th>AI / limit</th><th>Used</th><th>Remaining</th><th>Next reset</th><th></th></tr></thead><tbody>'+state.ais.map(function(ai){return ai.limits.map(function(l){var c=calc(l),percentValue=String(Math.round(c.usedPercent*10)/10);return '<tr><td><strong>'+esc(ai.name)+'</strong><small class="d-block text-muted">'+esc(windowLabel(l.windowHours))+'</small></td><td><div class="input-group input-group-sm"><input class="form-control" type="number" min="0" max="100" step="1" value="'+percentValue+'" data-aip-usage="'+ai.id+'|'+l.id+'" aria-label="Used percentage for '+esc(ai.name)+' '+esc(windowLabel(l.windowHours))+'"><span class="input-group-text">%</span></div></td><td>'+fmtNum(c.pct)+'%</td><td><input class="form-control form-control-sm" type="datetime-local" value="'+toLocalInput(l.resetAt)+'" data-aip-reset="'+ai.id+'|'+l.id+'" aria-label="Next reset for '+esc(ai.name)+' '+esc(windowLabel(l.windowHours))+'"></td><td><button class="btn btn-sm btn-secondary" data-aip-save-usage="'+ai.id+'|'+l.id+'" disabled>Save</button></td></tr>';}).join('');}).join('')+'</tbody></table></div>':'<div class="aip-empty"><i class="fas fa-edit"></i><h3>Nothing to update yet</h3><p>Add an AI with at least one limit, then return here for quick manual updates.</p><button class="btn btn-success" data-aip-action="add">Add AI</button></div>';
    var compare=root.querySelector('[data-aip-compare]'); if(compare) compare.innerHTML=state.ais.length?'<div class="aip-table-wrap"><table class="table aip-compare-table"><thead><tr><th>AI</th><th>Most restrictive limit</th><th>Remaining</th><th>Safe pace</th><th>Reset</th><th>Status</th></tr></thead><tbody>'+state.ais.map(function(ai){var h=health(ai), worst=ai.limits.length?ai.limits.map(function(l){return {limit:l,calc:calc(l)};}).reduce(function(a,b){return b.calc.pct<a.calc.pct?b:a;}):null;return '<tr><td><strong>'+esc(aiDisplayName(ai))+'</strong>'+(aiMeta(ai)?'<small class="d-block text-muted">'+esc(aiMeta(ai))+'</small>':'')+'</td><td>'+(worst?esc(windowLabel(worst.limit.windowHours)):'<span class="text-muted">No limits</span>')+'</td><td>'+(worst?fmtNum(worst.calc.pct)+'%':'—')+'</td><td>'+(worst?fmtNum(worst.calc.perHour)+'% / h':'—')+'</td><td>'+(worst?fmtDate(worst.limit.resetAt):'—')+'</td><td><span class="aip-health '+h.signal+'">'+(h.signal==='good'?'On track':h.signal==='warn'?'Watch pace':'Over pace')+'</span></td></tr>';}).join('')+'</tbody></table></div>':'<div class="aip-empty"><i class="fas fa-balance-scale"></i><h3>Nothing to compare yet</h3><p>Configure at least two AIs to make this view useful.</p><button class="btn btn-success" data-aip-action="add">Add AI</button></div>';
  }
  function modalInstance(){ if(window.bootstrap&&bootstrap.Modal){return bootstrap.Modal.getOrCreateInstance?bootstrap.Modal.getOrCreateInstance(modal):new bootstrap.Modal(modal);} return null; }
  function syncCustomName(){ var form=root.querySelector('[data-aip-form]'), provider=form.querySelector('[name="providerKey"]'), name=form.querySelector('[name="name"]'), wrap=root.querySelector('.aip-custom-name-wrap'), custom=provider.value==='custom'; wrap.classList.toggle('is-hidden',!custom); name.required=custom; name.disabled=!custom; if(!custom)name.value=providerName(provider.value); }
  function openEditor(id){ editingId=id||null; var ai=id?state.ais.find(function(a){return a.id===id;}):null, form=root.querySelector('[data-aip-form]'); form.reset(); form.querySelector('[name="aiId"]').value=ai?ai.id:''; form.querySelector('[name="providerKey"]').value=ai?ai.providerKey:'custom'; form.querySelector('[name="name"]').value=ai?ai.name:''; syncCustomName(); root.querySelector('.modal-title').textContent=ai?'Edit AI':'Add AI'; renderLimitEditor(ai?ai.limits:[defaultLimit()]); var instance=modalInstance(); if(instance){instance.show();}else if(window.jQuery){jQuery(modal).modal('show');} }
  function renderLimitEditor(limits){ root.querySelector('[data-aip-limit-editor]').innerHTML=limits.map(function(l){return '<div class="aip-limit-row" data-limit-row="'+l.id+'"><button type="button" class="btn btn-sm btn-outline-danger remove-limit" data-aip-remove-limit="'+l.id+'" aria-label="Remove this limit" title="Remove this limit"><i class="fas fa-trash-alt" aria-hidden="true"></i></button><div class="row g-2"><div class="col-md-4"><label class="form-label small">Window</label><select class="form-select form-select-sm" data-l-field="windowHours"><option value="5" '+(l.windowHours==5?'selected':'')+'>Session (5 hours)</option><option value="24" '+(l.windowHours==24?'selected':'')+'>Daily (24 hours)</option><option value="168" '+(l.windowHours==168?'selected':'')+'>Weekly (7 days)</option><option value="720" '+(l.windowHours==720?'selected':'')+'>Monthly (30 days)</option></select></div><div class="col-md-4"><label class="form-label small">Used now (%)</label><div class="input-group input-group-sm"><input class="form-control" type="number" min="0" max="100" step="1" data-l-field="usedPercent" value="'+esc(l.usedPercent)+'"><span class="input-group-text">%</span></div><small class="text-muted">Copy the percentage shown by the provider</small></div><div class="col-md-4"><label class="form-label small">Next reset (editable)</label><input class="form-control form-control-sm" type="datetime-local" data-l-field="resetAt" value="'+toLocalInput(l.resetAt)+'"></div></div></div>';}).join(''); }
  function toLocalInput(iso){ var d=new Date(iso), off=d.getTimezoneOffset()*60000; return new Date(d.getTime()-off).toISOString().slice(0,16); }
  function fromLocal(v){ var d=new Date(v); return isNaN(d)?new Date(Date.now()+168*3600000).toISOString():d.toISOString(); }
  function collectLimits(){ return Array.prototype.slice.call(root.querySelectorAll('[data-limit-row]')).map(function(row){function val(k){var e=row.querySelector('[data-l-field="'+k+'"]');return e?e.value:'';} var windowHours=Math.max(.1,Number(val('windowHours'))||168), usedPercent=Math.max(0,Math.min(100,Number(val('usedPercent'))||0)); return {id:row.getAttribute('data-limit-row'),label:windowLabel(windowHours),allowance:100,windowHours:windowHours,resetAt:fromLocal(val('resetAt')),usedPercent:usedPercent,used:usedPercent,updatedAt:new Date().toISOString()};}); }
  function enableUsageSave(e){var field=e.target.closest('[data-aip-usage],[data-aip-reset]');if(!field)return;var key=field.getAttribute('data-aip-usage')||field.getAttribute('data-aip-reset'),button=root.querySelector('[data-aip-save-usage="'+key+'"]');if(button){button.disabled=false;button.classList.remove('btn-secondary');button.classList.add('btn-primary');}}
  root.addEventListener('input',enableUsageSave); root.addEventListener('change',enableUsageSave);
  root.addEventListener('click',function(e){var t=e.target.closest('[data-aip-action],[data-aip-screen],[data-aip-edit],[data-aip-remove],[data-aip-update-ai],[data-aip-save-usage],[data-aip-remove-limit]');if(!t)return;if(t.dataset.aipScreen){setScreen(t.dataset.aipScreen);return;}if(t.dataset.aipAction==='add'){openEditor();return;}if(t.dataset.aipAction==='add-limit'){var ls=collectLimits();ls.push(defaultLimit());renderLimitEditor(ls);return;}if(t.dataset.aipRemoveLimit){var kept=collectLimits().filter(function(l){return l.id!==t.dataset.aipRemoveLimit;});if(!kept.length)kept.push(defaultLimit());renderLimitEditor(kept);return;}if(t.dataset.aipEdit){openEditor(t.dataset.aipEdit);return;}if(t.dataset.aipRemove){if(confirm('Remove this AI and its local usage data?')){state.ais=state.ais.filter(function(a){return a.id!==t.dataset.aipRemove;});save();}return;}if(t.dataset.aipUpdateAi){setScreen('update');return;}if(t.dataset.aipSaveUsage){var parts=t.dataset.aipSaveUsage.split('|'), input=root.querySelector('[data-aip-usage="'+t.dataset.aipSaveUsage+'"]'), resetInput=root.querySelector('[data-aip-reset="'+t.dataset.aipSaveUsage+'"]'),ai=state.ais.find(function(a){return a.id===parts[0]}),l=ai&&ai.limits.find(function(x){return x.id===parts[1]});if(l&&input){l.usedPercent=Math.max(0,Math.min(100,Number(input.value)||0));l.used=l.allowance*l.usedPercent/100;if(resetInput&&resetInput.value)l.resetAt=fromLocal(resetInput.value);l.updatedAt=new Date().toISOString();save();}}if(t.dataset.aipAction==='export'){var blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ai-usage-planner-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href);}});
  root.querySelector('[name="providerKey"]').addEventListener('change',syncCustomName);
  root.querySelector('[data-aip-form]').addEventListener('submit',function(e){e.preventDefault();var f=new FormData(e.target), providerKey=f.get('providerKey')||'custom', ai={id:f.get('aiId')||uid('ai'),name:providerKey==='custom'?String(f.get('name')).trim():providerName(providerKey),providerKey:providerKey,limits:collectLimits()};if(!ai.name){return;}var index=state.ais.findIndex(function(a){return a.id===ai.id;});if(index>=0)state.ais[index]=ai;else state.ais.push(ai);save();var instance=modalInstance();if(instance)instance.hide();else if(window.jQuery)jQuery(modal).modal('hide');setScreen('dashboard');});
  root.querySelector('[data-aip-import]').addEventListener('change',function(e){var file=e.target.files[0];if(!file)return;var reader=new FileReader();reader.onload=function(){try{var incoming=normalize(JSON.parse(reader.result));if(!Array.isArray(incoming.ais))throw new Error();if(confirm('Replace your current planner data with this file?')){state=incoming;save();setScreen('dashboard');}}catch(err){alert('This file is not a valid AI Usage Planner JSON export.');}e.target.value='';};reader.readAsText(file);});
  function rollExpired(){state.ais.forEach(function(ai){ai.limits.forEach(function(l){var reset=new Date(l.resetAt), now=Date.now(), step=Math.max(.1,l.windowHours)*3600000;if(reset.getTime()<=now){var jumps=Math.floor((now-reset.getTime())/step)+1;l.resetAt=new Date(reset.getTime()+jumps*step).toISOString();l.used=0;l.updatedAt=new Date().toISOString();}});});}
  rollExpired(); save(); setScreen(activeScreen); setInterval(function(){render();},60000);
})();
</script>
