<div class="tool-widget widget-application-cfc-generator">
  <div class="appcfc-import"><label for="appcfc-file"><i class="fas fa-file-import"></i> <cfif local.isEs>Importar Application.cfc existente<cfelse>Import existing Application.cfc</cfif></label><div class="appcfc-import-controls"><input id="appcfc-file" type="file" accept=".cfc,.cfm,text/plain"><button type="button" class="tool-copy" id="appcfc-import-button"><i class="fas fa-upload"></i> <cfif local.isEs>Parsear archivo<cfelse>Parse file</cfif></button></div><p class="appcfc-helper"><cfif local.isEs>Se detectan funciones, configuraciones básicas y código fuera de las funciones.<cfelse>Functions, basic settings, and code outside functions are detected.</cfif></p></div>
  <div class="appcfc-form-grid">
    <div><label for="appcfc-engine"><cfif local.isEs>Motor CFML<cfelse>CFML engine</cfif></label><select id="appcfc-engine"><option value="Lucee">Lucee</option><option value="Adobe ColdFusion">Adobe ColdFusion</option></select></div>
    <div><label for="appcfc-format"><cfif local.isEs>Formato de salida<cfelse>Output format</cfif></label><select id="appcfc-format"><option value="script">CFScript</option><option value="tag"><cfif local.isEs>Tags CFML<cfelse>CFML tags</cfif></option></select></div>
    <div><label for="appcfc-name"><cfif local.isEs>Nombre de la aplicación<cfelse>Application name</cfif></label><input id="appcfc-name" value="MyApplication" placeholder="MyApplication"></div>
    <div><label for="appcfc-application-timeout"><cfif local.isEs>Timeout de aplicación (minutos)<cfelse>Application timeout (minutes)</cfif></label><input id="appcfc-application-timeout" type="number" min="1" value="1440"></div>
    <div><label for="appcfc-session-timeout"><cfif local.isEs>Timeout de sesión (minutos)<cfelse>Session timeout (minutes)</cfif></label><input id="appcfc-session-timeout" type="number" min="1" value="30"></div>
    <div><label for="appcfc-session-management"><cfif local.isEs>¿Habilitar sesiones?<cfelse>Enable sessions?</cfif></label><select id="appcfc-session-management"><option value="true"><cfif local.isEs>Sí<cfelse>Yes</cfif></option><option value="false"><cfif local.isEs>No<cfelse>No</cfif></option></select></div>
    <div><label for="appcfc-client"><cfif local.isEs>¿Habilitar client scope?<cfelse>Enable client scope?</cfif></label><select id="appcfc-client"><option value="false"><cfif local.isEs>No<cfelse>No</cfif></option><option value="true"><cfif local.isEs>Sí<cfelse>Yes</cfif></option></select></div>
    <div><label for="appcfc-client-cookies"><cfif local.isEs>¿Usar cookies de cliente?<cfelse>Use client cookies?</cfif></label><select id="appcfc-client-cookies"><option value="true"><cfif local.isEs>Sí<cfelse>Yes</cfif></option><option value="false"><cfif local.isEs>No<cfelse>No</cfif></option></select></div>
    <div><label for="appcfc-orm"><cfif local.isEs>¿Habilitar ORM?<cfelse>Enable ORM?</cfif></label><select id="appcfc-orm"><option value="false"><cfif local.isEs>No<cfelse>No</cfif></option><option value="true"><cfif local.isEs>Sí<cfelse>Yes</cfif></option></select></div>
    <div><label for="appcfc-datasource-general"><cfif local.isEs>Datasource general<cfelse>General datasource</cfif></label><input id="appcfc-datasource-general" placeholder="myDatasource"></div>
    <div><label for="appcfc-datasource"><cfif local.isEs>Datasource ORM<cfelse>ORM datasource</cfif></label><input id="appcfc-datasource" placeholder="myDatasource"></div>
    <div><label for="appcfc-script-protect">scriptProtect</label><input id="appcfc-script-protect" placeholder="all"></div>
    <div><label for="appcfc-secure-json"><cfif local.isEs>¿Habilitar secureJSON?<cfelse>Enable secureJSON?</cfif></label><select id="appcfc-secure-json"><option value="false"><cfif local.isEs>No<cfelse>No</cfif></option><option value="true"><cfif local.isEs>Sí<cfelse>Yes</cfif></option></select></div>
    <div><label for="appcfc-secure-json-prefix">secureJSONPrefix</label><input id="appcfc-secure-json-prefix" placeholder=""></div>
    <div class="appcfc-wide"><label for="appcfc-mappings"><cfif local.isEs>Mappings (uno por línea)<cfelse>Mappings (one per line)</cfif></label><textarea id="appcfc-mappings" rows="3" placeholder='/models=/models<br>/includes=/includes'></textarea></div>
    <div class="appcfc-wide"><label for="appcfc-outside"><cfif local.isEs>Código fuera de las funciones<cfelse>Code outside functions</cfif></label><textarea id="appcfc-outside" rows="5" placeholder='<cfif local.isEs>// Variables, imports o configuración global<br>// Se conserva al regenerar el archivo<cfelse>// Variables, imports, or global configuration<br>// Preserved when regenerating the file</cfif>'></textarea></div>
    <div><label for="appcfc-cors"><cfif local.isEs>Access-Control-Allow-Origin<cfelse>Access-Control-Allow-Origin</cfif></label><input id="appcfc-cors" value="" placeholder="https://ejemplo.com"></div>
    <div><label for="appcfc-errors"><cfif local.isEs>Manejo de errores<cfelse>Error handling</cfif></label><select id="appcfc-errors"><option value="development"><cfif local.isEs>Desarrollo<cfelse>Development</cfif></option><option value="production"><cfif local.isEs>Producción<cfelse>Production</cfif></option></select></div>
  </div>
  <div class="appcfc-custom-functions"><h3><i class="fas fa-puzzle-piece"></i> <cfif local.isEs>Funciones personalizadas<cfelse>Custom functions</cfif></h3><p class="appcfc-helper"><cfif local.isEs>Agregá bloques de funciones para incluirlos en tu Application.cfc.<cfelse>Add function blocks to include in your Application.cfc.</cfif></p><div id="appcfc-functions"></div><button type="button" class="tool-copy" id="appcfc-add-function"><i class="fas fa-plus"></i> <cfif local.isEs>Agregar función<cfelse>Add function</cfif></button></div>
  <div class="widget-buttons"><button type="button" class="btn-social btn-upwork" id="appcfc-generate"><i class="fas fa-wand-magic-sparkles"></i> <cfif local.isEs>Generar Application.cfc<cfelse>Generate Application.cfc</cfif></button><button type="button" class="tool-copy" data-copy-target="appcfc-output"><i class="far fa-copy"></i> <cfif local.isEs>Copiar código<cfelse>Copy code</cfif></button><button type="button" class="tool-copy" id="appcfc-download"><i class="fas fa-download"></i> <cfif local.isEs>Descargar CFC<cfelse>Download CFC</cfif></button></div>
  <p class="tool-message" id="appcfc-message" aria-live="polite"></p><label for="appcfc-output"><cfif local.isEs>Application.cfc generado<cfelse>Generated Application.cfc</cfif></label><textarea id="appcfc-output" rows="24" readonly spellcheck="false"></textarea>
</div>
<script type="text/plain" data-legacy-generator="true">
(function(){var engine=document.getElementById('appcfc-engine'),name=document.getElementById('appcfc-name'),timeout=document.getElementById('appcfc-session-timeout'),client=document.getElementById('appcfc-client'),orm=document.getElementById('appcfc-orm'),datasource=document.getElementById('appcfc-datasource'),mappings=document.getElementById('appcfc-mappings'),cors=document.getElementById('appcfc-cors'),errors=document.getElementById('appcfc-errors'),output=document.getElementById('appcfc-output'),message=document.getElementById('appcfc-message'),es=<cfif local.isEs>true<cfelse>false</cfif>;
function val(el){return el.value.trim();}function generate(){var app=val(name)||'MyApplication',lines=['component {','    this.name = "'+app.replace(/"/g,'\\"')+'";','    this.applicationTimeout = createTimeSpan(1, 0, 0, 0);','    this.sessionManagement = true;','    this.sessionTimeout = createTimeSpan(0, 0, '+(Number(timeout.value)||30)+', 0);','    this.setClientCookies = true;'];if(client.value==='true')lines.push('    this.clientManagement = true;');if(orm.value==='true'){lines.push('','    this.ormEnabled = true;');if(val(datasource))lines.push('    this.ormSettings = {datasource: "'+val(datasource).replace(/"/g,'\\"')+'", flushAtRequestEnd: false};');else lines.push('    this.ormSettings = {flushAtRequestEnd: false};');}if(val(cors))lines.push('','    // Review the allowed origin before deploying to production.','    this.corsOrigin = "'+val(cors).replace(/"/g,'\\"')+'";');if(engine.value==='Adobe ColdFusion')lines.push('','    // Adobe ColdFusion project starter. Verify engine-specific settings before production.');else lines.push('','    // Lucee project starter. Verify engine-specific settings before production.');lines.push('','    public boolean function onApplicationStart() {','        return true;','    }','','    public boolean function onRequestStart(required string targetPage) {','        return true;','    }');if(errors.value==='development')lines.push('','    public void function onError(required any exception, required string eventName) {','        writeDump(var=arguments.exception, label="Application error");','    }');else lines.push('','    public void function onError(required any exception, required string eventName) {','        // Log the exception and show a generic error page in production.','        writeLog(type="error", text=serializeJSON(arguments.exception));','    }');var mapLines=val(mappings).split(/\r?\n/).filter(Boolean);if(mapLines.length){lines.splice(2,0,'    this.mappings = {};');mapLines.forEach(function(item){var parts=item.split('=');if(parts.length>=2)lines.splice(3,0,'    this.mappings["'+parts[0].trim()+'"] = "'+parts.slice(1).join('=').trim()+'";';});}lines.push('','}');output.value=lines.join('\n');message.textContent=es?'Application.cfc generado. Revisá los comentarios antes de usarlo en producción.':'Application.cfc generated. Review the comments before using it in production.';message.className='tool-message';}document.getElementById('appcfc-generate').addEventListener('click',generate);document.getElementById('appcfc-download').addEventListener('click',function(){if(!output.value)generate();var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([output.value],{type:'text/plain'}));a.download='Application.cfc';a.click();URL.revokeObjectURL(a.href);});generate();}());
</script>
<script>
(function(){
  var button=document.getElementById('appcfc-generate'),download=document.getElementById('appcfc-download'),output=document.getElementById('appcfc-output'),message=document.getElementById('appcfc-message'),functionList=document.getElementById('appcfc-functions'),fileInput=document.getElementById('appcfc-file'),outside=document.getElementById('appcfc-outside'),es=<cfif local.isEs>true<cfelse>false</cfif>;
  function get(id){return document.getElementById(id).value.trim();}
  function autoGrow(field){if(!field)return;field.style.height='auto';field.style.height=Math.max(field.scrollHeight,80)+'px';}
  function bindAutoGrow(field){if(!field||field.dataset.autoGrow==='true')return;field.dataset.autoGrow='true';field.addEventListener('input',function(){autoGrow(field);});autoGrow(field);}
  function bindAllAutoGrow(){bindAutoGrow(outside);bindAutoGrow(output);functionList.querySelectorAll('.appcfc-function-body').forEach(bindAutoGrow);}
  var autoGrowObserver=new MutationObserver(function(){bindAllAutoGrow();});autoGrowObserver.observe(functionList,{childList:true});
  function addFunction(prefill){var row=document.createElement('div');row.className='appcfc-function-row';row.innerHTML='<div><label>Evento Application.cfc</label><select class="appcfc-function-name"><option value="onApplicationStart">onApplicationStart</option><option value="onApplicationEnd">onApplicationEnd</option><option value="onSessionStart">onSessionStart</option><option value="onSessionEnd">onSessionEnd</option><option value="onRequestStart">onRequestStart</option><option value="onRequest">onRequest</option><option value="onRequestEnd">onRequestEnd</option><option value="onCFCRequest">onCFCRequest</option><option value="onError">onError</option><option value="onMissingTemplate">onMissingTemplate</option><option value="onAbort">onAbort</option><option value="onServerStart">onServerStart</option></select></div><div><label>Acceso</label><select class="appcfc-function-access"><option value="public">public</option><option value="private">private</option></select></div><div><label>Tipo de retorno</label><input class="appcfc-function-return" value="void"></div><div class="appcfc-function-body-wrap"><label>Cuerpo de la función</label><textarea class="appcfc-function-body" rows="3" placeholder="// Código CFML"></textarea></div><button type="button" class="tool-copy appcfc-remove-function"><i class="fas fa-trash"></i> Eliminar</button>';row.querySelector('.appcfc-remove-function').addEventListener('click',function(){row.remove();});functionList.appendChild(row);if(prefill){row.querySelector('.appcfc-function-name').value=prefill.name;row.querySelector('.appcfc-function-access').value=prefill.access||'public';row.querySelector('.appcfc-function-return').value=prefill.returntype||'void';row.querySelector('.appcfc-function-body').value=prefill.body||'';}}
  function getFunctions(){return Array.from(functionList.querySelectorAll('.appcfc-function-row')).map(function(row){return {name:row.querySelector('.appcfc-function-name').value.trim()||'miFuncion',access:row.querySelector('.appcfc-function-access').value,returntype:row.querySelector('.appcfc-function-return').value.trim()||'void',body:row.querySelector('.appcfc-function-body').value.trim()};});}
  function signature(name){var map={onApplicationEnd:'struct applicationScope',onSessionStart:'struct sessionScope, struct applicationScope',onSessionEnd:'struct sessionScope, struct applicationScope',onRequestStart:'string targetPage',onRequest:'string targetPage',onRequestEnd:'',onCFCRequest:'string cfcname, string method, struct args, struct metadata',onError:'any exception, string eventName',onMissingTemplate:'string targetPage',onAbort:'',onServerStart:''};return map[name]||'';}
  function tagArguments(name,lt){var map={onApplicationEnd:[lt+'cfargument name="applicationScope" type="struct" required="true">'],onSessionStart:[lt+'cfargument name="sessionScope" type="struct" required="true">',lt+'cfargument name="applicationScope" type="struct" required="true">'],onSessionEnd:[lt+'cfargument name="sessionScope" type="struct" required="true">',lt+'cfargument name="applicationScope" type="struct" required="true">'],onRequestStart:[lt+'cfargument name="targetPage" type="string" required="true">'],onRequest:[lt+'cfargument name="targetPage" type="string" required="true">'],onCFCRequest:[lt+'cfargument name="cfcname" type="string" required="true">',lt+'cfargument name="method" type="string" required="true">',lt+'cfargument name="args" type="struct" required="false">',lt+'cfargument name="metadata" type="struct" required="false">'],onError:[lt+'cfargument name="exception" required="true">',lt+'cfargument name="eventName" type="string" required="true">'],onMissingTemplate:[lt+'cfargument name="targetPage" type="string" required="true">']};return map[name]||[];}
  function importedValue(text,pattern){var match=text.match(pattern);return match?match[1]:'';}
  function parseImported(text){var lt=String.fromCharCode(60),isTag=new RegExp(lt+'cffunction\\b','i').test(text),functionListEl=functionList;functionListEl.innerHTML='';var outsideText=text;if(isTag){var tagFunction=new RegExp(lt+'cffunction\\b([^>]*)>[\\s\\S]*?'+lt+'/cffunction>','gi'),match;while((match=tagFunction.exec(text))!==null){var attrs=match[1],body=match[0].replace(new RegExp('^'+lt+'cffunction\\b[^>]*>','i'),'').replace(new RegExp(lt+'/cffunction>\\s*$','i'),'').replace(new RegExp(lt+'cfargument\\b[^>]*>','gi'),'').trim(),nameMatch=attrs.match(/name\s*=\s*["']([^"']+)["']/i),accessMatch=attrs.match(/access\s*=\s*["']([^"']+)["']/i),returnMatch=attrs.match(/returntype\s*=\s*["']([^"']+)["']/i);if(nameMatch)addFunction({name:nameMatch[1],access:accessMatch?accessMatch[1]:'public',returntype:returnMatch?returnMatch[1]:'void',body:body});}outsideText=text.replace(tagFunction,'').replace(new RegExp(lt+'/?cfcomponent\\b[^>]*>','gi'),'').trim();}else{var scriptFunction=/\b(?:(public|private|remote)\s+)?(?:(\w+)\s+)?function\s+(\w+)\s*\(([^)]*)\)\s*\{/gi,ranges=[],match;while((match=scriptFunction.exec(text))!==null){var depth=1,pos=scriptFunction.lastIndex;while(pos<text.length&&depth){if(text[pos]==='{')depth++;else if(text[pos]==='}')depth--;pos++;}var body=text.slice(scriptFunction.lastIndex,pos-1).trim();addFunction({name:match[3],access:match[1]||'public',returntype:match[2]||'void',body:body});ranges.push([match.index,pos]);scriptFunction.lastIndex=pos;}ranges.reverse().forEach(function(range){text=text.slice(0,range[0])+text.slice(range[1]);});outsideText=text.replace(/^\s*component\s*\{/, '').replace(/\}\s*$/,'').trim();}
    outsideText=outsideText.split(/\r?\n/).filter(function(line){return !/^\s*this\.(?:name|applicationTimeout|sessionManagement|sessionTimeout|clientManagement|setClientCookies|clientCookies|datasource|ormEnabled|ormSettings|scriptProtect|secureJSON|secureJSONPrefix|corsOrigin|mappings)\b/i.test(line);}).join('\n').trim();var appName=importedValue(text,/this\.name\s*=\s*["']([^"']+)["']/i);if(appName)document.getElementById('appcfc-name').value=appName;var session=importedValue(text,/sessionTimeout\s*=\s*createTimeSpan\(\s*0\s*,\s*0\s*,\s*(\d+)/i);if(session)document.getElementById('appcfc-session-timeout').value=session;var appTimeout=importedValue(text,/applicationTimeout\s*=\s*createTimeSpan\(\s*0\s*,\s*0\s*,\s*(\d+)/i);if(appTimeout)document.getElementById('appcfc-application-timeout').value=appTimeout;document.getElementById('appcfc-session-management').value=/sessionManagement\s*=\s*true/i.test(text)?'true':'false';document.getElementById('appcfc-client').value=/clientManagement\s*=\s*true/i.test(text)?'true':'false';document.getElementById('appcfc-client-cookies').value=/setClientCookies\s*=\s*false/i.test(text)?'false':'true';document.getElementById('appcfc-orm').value=/ormEnabled\s*=\s*true/i.test(text)?'true':'false';var ds=importedValue(text,/ormSettings\s*=\s*\{[^}]*datasource\s*[:=]\s*["']([^"']+)["']/i);if(ds)document.getElementById('appcfc-datasource').value=ds;var generalDs=importedValue(text,/this\.datasource\s*=\s*["']([^"']+)["']/i);if(generalDs)document.getElementById('appcfc-datasource-general').value=generalDs;var protect=importedValue(text,/scriptProtect\s*=\s*["']([^"']+)["']/i);if(protect)document.getElementById('appcfc-script-protect').value=protect;document.getElementById('appcfc-secure-json').value=/secureJSON\s*=\s*true/i.test(text)?'true':'false';var securePrefix=importedValue(text,/secureJSONPrefix\s*=\s*["']([^"']+)["']/i);if(securePrefix)document.getElementById('appcfc-secure-json-prefix').value=securePrefix;var corsValue=importedValue(text,/corsOrigin\s*=\s*["']([^"']+)["']/i);if(corsValue)document.getElementById('appcfc-cors').value=corsValue;var mappingMatches=[],mappingRegex=/mappings(?:\[|\.)["']?([^\]"'=]+)["']?\]?\s*(?:\]|=)\s*["']([^"']+)["']/gi,mappingMatch;while((mappingMatch=mappingRegex.exec(text))!==null)mappingMatches.push(mappingMatch[1]+'='+mappingMatch[2]);document.getElementById('appcfc-mappings').value=mappingMatches.join('\n');outside.value=outsideText;document.getElementById('appcfc-format').value=isTag?'tag':'script';message.textContent=es?'Archivo analizado. Revisá los campos y generá el nuevo Application.cfc.':'File parsed. Review the fields and generate the new Application.cfc.';message.className='tool-message';}
  function importFile(){var file=fileInput.files[0];if(!file){message.textContent=es?'Elegí un archivo Application.cfc.':'Choose an Application.cfc file.';message.className='tool-message is-error';return;}var reader=new FileReader();reader.onload=function(){parseImported(reader.result);bindAllAutoGrow();autoGrow(outside);};reader.readAsText(file);}
  function generateApplication(){
    var app=(get('appcfc-name')||'MyApplication').split('"').join('\\"'),minutes=Number(document.getElementById('appcfc-session-timeout').value)||30,lines=[];
    if(get('appcfc-format')==='tag'){
      var lt=String.fromCharCode(60),appMinutes=Number(document.getElementById('appcfc-application-timeout').value)||1440,tagLines=[lt+'cfcomponent output="false">',lt+'cfset this.name = "'+app+'">',lt+'cfset this.applicationTimeout = createTimeSpan(0, 0, '+appMinutes+', 0)>',lt+'cfset this.sessionManagement = '+get('appcfc-session-management')+'>',lt+'cfset this.sessionTimeout = createTimeSpan(0, 0, '+minutes+', 0)>',lt+'cfset this.setClientCookies = '+get('appcfc-client-cookies')+'>'];
      if(get('appcfc-client')==='true')tagLines.push(lt+'cfset this.clientManagement = true>');
      if(get('appcfc-orm')==='true'){tagLines.push(lt+'cfset this.ormEnabled = true>');if(get('appcfc-datasource'))tagLines.push(lt+'cfset this.ormSettings = {datasource: "'+get('appcfc-datasource').split('"').join('\\"')+'", flushAtRequestEnd: false}>');}
      if(get('appcfc-datasource-general'))tagLines.push(lt+'cfset this.datasource = "'+get('appcfc-datasource-general').split('"').join('\\"')+'">');if(get('appcfc-script-protect'))tagLines.push(lt+'cfset this.scriptProtect = "'+get('appcfc-script-protect').split('"').join('\\"')+'">');if(get('appcfc-secure-json')==='true')tagLines.push(lt+'cfset this.secureJSON = true>');if(get('appcfc-secure-json-prefix'))tagLines.push(lt+'cfset this.secureJSONPrefix = "'+get('appcfc-secure-json-prefix').split('"').join('\\"')+'">');
      var tagMappings=get('appcfc-mappings').split(/\r?\n/).filter(Boolean);if(tagMappings.length){tagLines.push(lt+'cfset this.mappings = {}>');tagMappings.forEach(function(item){var pair=item.split('=');if(pair.length>1)tagLines.push(lt+'cfset this.mappings["'+pair[0].trim()+'"] = "'+pair.slice(1).join('=').trim()+'">');});}
      if(get('appcfc-cors'))tagLines.push(lt+'cfset this.corsOrigin = "'+get('appcfc-cors').split('"').join('\\"')+'">');
      if(get('appcfc-outside'))tagLines.push('',get('appcfc-outside').split(/\r?\n/).join('\n'));
      tagLines.push('',lt+'cffunction name="onApplicationStart" returntype="boolean" output="false">', '    '+lt+'cfreturn true>',lt+'/cffunction>','',lt+'cffunction name="onRequestStart" returntype="boolean" output="false">','    '+lt+'cfargument name="targetPage" type="string" required="true">','    '+lt+'cfreturn true>',lt+'/cffunction>');
      if(get('appcfc-errors')==='development')tagLines.push('',lt+'cffunction name="onError" returntype="void" output="true">','    '+lt+'cfargument name="exception" required="true">','    '+lt+'cfdump var="#arguments.exception#">',lt+'/cffunction>');else tagLines.push('',lt+'cffunction name="onError" returntype="void" output="false">','    '+lt+'cfargument name="exception" required="true">','    '+lt+'cflog type="error" text="#serializeJSON(arguments.exception)#">',lt+'/cffunction>');
      getFunctions().forEach(function(fn){var fnArgs=tagArguments(fn.name,lt),fnBlock=['',lt+'cffunction name="'+fn.name+'" access="'+fn.access+'" returntype="'+fn.returntype+'" output="false">'];fnArgs.forEach(function(arg){fnBlock.push('    '+arg);});fnBlock.push(fn.body?'    '+fn.body.split(/\r?\n/).join('\n    '):'    '+lt+'cfreturn>','    '+lt+'/cffunction>');tagLines.push.apply(tagLines,fnBlock);});tagLines.push('',lt+'/cfcomponent>');output.value=tagLines.join('\n');message.textContent=es?'Application.cfc en tags generado correctamente.':'Tag-based Application.cfc generated successfully.';message.className='tool-message';return;
    }
    var appMinutesScript=Number(document.getElementById('appcfc-application-timeout').value)||1440;lines.push('component {','    this.name = "'+app+'";','    this.applicationTimeout = createTimeSpan(0, 0, '+appMinutesScript+', 0);','    this.sessionManagement = '+get('appcfc-session-management')+';','    this.sessionTimeout = createTimeSpan(0, 0, '+minutes+', 0);','    this.setClientCookies = '+get('appcfc-client-cookies')+';');
    if(get('appcfc-client')==='true')lines.push('    this.clientManagement = true;');
    if(get('appcfc-orm')==='true'){lines.push('','    this.ormEnabled = true;');if(get('appcfc-datasource'))lines.push('    this.ormSettings = {datasource: "'+get('appcfc-datasource').split('"').join('\\"')+'", flushAtRequestEnd: false};');}
    if(get('appcfc-datasource-general'))lines.push('    this.datasource = "'+get('appcfc-datasource-general').split('"').join('\\"')+'";');if(get('appcfc-script-protect'))lines.push('    this.scriptProtect = "'+get('appcfc-script-protect').split('"').join('\\"')+'";');if(get('appcfc-secure-json')==='true')lines.push('    this.secureJSON = true;');if(get('appcfc-secure-json-prefix'))lines.push('    this.secureJSONPrefix = "'+get('appcfc-secure-json-prefix').split('"').join('\\"')+'";');
    var mappingLines=get('appcfc-mappings').split(/\r?\n/).filter(Boolean);if(mappingLines.length){lines.push('','    this.mappings = {};');mappingLines.forEach(function(item){var pair=item.split('=');if(pair.length>1)lines.push('    this.mappings["'+pair[0].trim()+'"] = "'+pair.slice(1).join('=').trim()+'";');});}
    if(get('appcfc-cors'))lines.push('','    // Review the allowed origin before deploying.','    this.corsOrigin = "'+get('appcfc-cors').split('"').join('\\"')+'";');
    if(get('appcfc-outside'))lines.push('',get('appcfc-outside').split(/\r?\n/).join('\n'));
    lines.push('','    public boolean function onApplicationStart() {','        return true;','    }','','    public boolean function onRequestStart(required string targetPage) {','        return true;','    }');
    if(get('appcfc-errors')==='development')lines.push('','    public void function onError(required any exception, required string eventName) {','        writeDump(var=arguments.exception, label="Application error");','    }');else lines.push('','    public void function onError(required any exception, required string eventName) {','        writeLog(type="error", text=serializeJSON(arguments.exception));','    }');
    getFunctions().forEach(function(fn){lines.push('','    '+fn.access+' '+fn.returntype+' function '+fn.name+'('+signature(fn.name)+') {',fn.body?'        '+fn.body.split(/\r?\n/).join('\n        '):'        // Add function logic here.','    }');});lines.push('','}');output.value=lines.join('\n');message.textContent=es?'Application.cfc generado correctamente.':'Application.cfc generated successfully.';message.className='tool-message';
  }
  document.getElementById('appcfc-add-function').addEventListener('click',function(){addFunction();});document.getElementById('appcfc-import-button').addEventListener('click',importFile);button.addEventListener('click',function(){generateApplication();autoGrow(output);});download.addEventListener('click',function(){if(!output.value){generateApplication();autoGrow(output);}var link=document.createElement('a');link.href=URL.createObjectURL(new Blob([output.value],{type:'text/plain'}));link.download='Application.cfc';link.click();URL.revokeObjectURL(link.href);});bindAllAutoGrow();generateApplication();autoGrow(output);
}());
</script>
