<div class="tool-widget widget-cfml-orm-entity-generator">
  <div class="orm-entity-options"><div><label for="orm-entity-name"><cfif local.isEs>Nombre de la entidad<cfelse>Entity name</cfif></label><input id="orm-entity-name" value="User"></div><div><label for="orm-entity-table"><cfif local.isEs>Tabla<cfelse>Table</cfif></label><input id="orm-entity-table" value="users"></div><div><label for="orm-entity-format"><cfif local.isEs>Formato de salida<cfelse>Output format</cfif></label><select id="orm-entity-format" class="orm-entity-select"><option value="script">CFScript</option><option value="tag">CFML tags</option></select></div></div>
  <label for="orm-entity-columns"><cfif local.isEs>Columnas (una por línea)<cfelse>Columns (one per line)</cfif></label><textarea id="orm-entity-columns" rows="9" spellcheck="false" placeholder="id INT PK&#10;name VARCHAR(100)&#10;email VARCHAR(150)&#10;created_at DATETIME"></textarea>
  <label for="orm-entity-relations"><cfif local.isEs>Relaciones opcionales (nombre | tipo | fk | entidad)<cfelse>Optional relationships (name | type | fk | entity)</cfif></label><textarea id="orm-entity-relations" rows="4" spellcheck="false" placeholder="posts | one-to-many | user_id | Post"></textarea>
  <div class="widget-buttons"><button type="button" class="btn-social btn-upwork" id="orm-entity-generate"><i class="fas fa-wand-magic-sparkles"></i> <cfif local.isEs>Generar entidad<cfelse>Generate entity</cfif></button><button type="button" class="tool-copy" data-copy-target="orm-entity-output"><i class="far fa-copy"></i> <cfif local.isEs>Copiar código<cfelse>Copy code</cfif></button><button type="button" class="tool-copy" id="orm-entity-download"><i class="fas fa-download"></i> <cfif local.isEs>Descargar CFC<cfelse>Download CFC</cfif></button></div>
  <p class="tool-message" id="orm-entity-message" aria-live="polite"></p><label for="orm-entity-output"><cfif local.isEs>Entidad generada<cfelse>Generated entity</cfif></label><textarea id="orm-entity-output" rows="20" readonly spellcheck="false"></textarea>
</div>
<script>
(function(){var name=document.getElementById('orm-entity-name'),table=document.getElementById('orm-entity-table'),format=document.getElementById('orm-entity-format'),columns=document.getElementById('orm-entity-columns'),relations=document.getElementById('orm-entity-relations'),output=document.getElementById('orm-entity-output'),message=document.getElementById('orm-entity-message'),es=<cfif local.isEs>true<cfelse>false</cfif>,lt=String.fromCharCode(60),gt=String.fromCharCode(62);
function camel(value){return value.trim().toLowerCase().replace(/[_-]+([a-z0-9])/g,function(_,c){return c.toUpperCase();});}
function typeInfo(type){var raw=type.toLowerCase(),length=(raw.match(/[0-9]+/)||[])[0]||'',base=raw.replace(/\(.*/,'');if(/int|bigint|smallint|tinyint/.test(base))return {orm:'integer',type:'numeric',length:''};if(/decimal|numeric|float|double/.test(base))return {orm:'bigDecimal',type:'numeric',length:''};if(/date|time/.test(base))return {orm:/datetime|timestamp/.test(base)?'timestamp':'date',type:'date',length:''};if(/bit|bool/.test(base))return {orm:'boolean',type:'boolean',length:''};if(/text|char|clob|varchar/.test(base))return {orm:'string',type:'string',length:length};return {orm:'string',type:'string',length:length};}
function parseColumns(){return columns.value.split(/\r?\n/).map(function(line){var text=line.trim();if(!text)return null;var parts=text.split(/\s+/),column=parts.shift(),definition=parts.join(' '),primary=/\b(?:pk|primary(?:key)?)\b/i.test(definition),info=typeInfo(definition);return {column:column,name:camel(column),primary:primary,orm:info.orm,type:info.type,length:info.length};}).filter(Boolean);}
function parseRelations(){return relations.value.split(/\r?\n/).map(function(line){var p=line.split('|').map(function(v){return v.trim();});if(p.length<4)return null;return {name:camel(p[0]),kind:p[1].toLowerCase(),fk:p[2],entity:p[3]};}).filter(Boolean);}
function generate(){var entity=name.value.trim()||'Entity',tbl=table.value.trim()||camel(entity),cols=parseColumns(),rels=parseRelations();if(!cols.length){message.textContent=es?'Agregá al menos una columna.':'Add at least one column.';message.className='tool-message is-error';return;}if(format.value==='tag'){var tagLines=[lt+'cfcomponent persistent="true" table="'+tbl+'"'+gt];cols.forEach(function(col){var attrs=' name="'+col.name+'" column="'+col.column+'" ormtype="'+col.orm+'"';if(col.primary)attrs+=' fieldtype="id" generator="identity"';if(col.length)attrs+=' length="'+col.length+'"';tagLines.push('    '+lt+'cfproperty'+attrs+gt);});rels.forEach(function(rel){var attr=' name="'+rel.name+'" fieldtype="'+rel.kind+'" cfc="'+rel.entity+'"';if(rel.fk)attr+=' fkcolumn="'+rel.fk+'"';tagLines.push('    '+lt+'cfproperty'+attr+gt);});tagLines.push(lt+'/cfcomponent'+gt);output.value=tagLines.join('\n');}else{var lines=['component persistent="true" table="'+tbl+'" {'];cols.forEach(function(col){lines.push('','    property name="'+col.name+'" column="'+col.column+'" ormtype="'+col.orm+'"'+(col.primary?' fieldtype="id" generator="identity"':'')+(col.length?' length="'+col.length+'"':'')+';');});rels.forEach(function(rel){lines.push('','    property name="'+rel.name+'" fieldtype="'+rel.kind+'" cfc="'+rel.entity+'"'+(rel.fk?' fkcolumn="'+rel.fk+'"':'')+';');});lines.push('','}');output.value=lines.join('\n');}message.textContent=es?'Entidad ORM generada. Revisá tipos y relaciones antes de usarla.':'ORM entity generated. Review types and relationships before using it.';message.className='tool-message';}
document.getElementById('orm-entity-generate').addEventListener('click',generate);format.addEventListener('change',function(){if(columns.value.trim())generate();});document.getElementById('orm-entity-download').addEventListener('click',function(){if(!output.value)generate();var link=document.createElement('a');link.href=URL.createObjectURL(new Blob([output.value],{type:'text/plain'}));link.download=(name.value.trim()||'Entity')+'.cfc';link.click();URL.revokeObjectURL(link.href);});}());
</script>
