<div class="tool-widget widget-cfml-tag-script-converter">
  <div class="cfml-converter-options">
    <div><label for="cfml-converter-direction"><cfif local.isEs>Conversión<cfelse>Conversion</cfif></label><select id="cfml-converter-direction"><option value="tag-script"><cfif local.isEs>Tag CFML → CFScript<cfelse>CFML tags → CFScript</cfif></option><option value="script-tag"><cfif local.isEs>CFScript → Tag CFML<cfelse>CFScript → CFML tags</cfif></option></select></div>
    <div><label for="cfml-converter-indent"><cfif local.isEs>Indentación<cfelse>Indentation</cfif></label><select id="cfml-converter-indent"><option value="4">4 espacios</option><option value="2">2 espacios</option><option value="tab">Tabulaciones</option></select></div>
  </div>
  <div class="cfml-converter-grid"><div><label for="cfml-converter-input"><cfif local.isEs>Código de entrada<cfelse>Input code</cfif></label><textarea id="cfml-converter-input" rows="16" spellcheck="false" placeholder="&lt;cfset nombre = &quot;Flavio&quot;&gt;&#10;&lt;cfoutput&gt;#nombre#&lt;/cfoutput&gt;"></textarea></div><div><label for="cfml-converter-output"><cfif local.isEs>Resultado<cfelse>Result</cfif></label><textarea id="cfml-converter-output" rows="16" readonly spellcheck="false"></textarea></div></div>
  <div class="widget-buttons"><button type="button" class="btn-social btn-upwork" id="cfml-converter-convert"><i class="fas fa-wand-magic-sparkles"></i> <cfif local.isEs>Convertir código<cfelse>Convert code</cfif></button><button type="button" class="tool-copy" id="cfml-converter-swap"><i class="fas fa-right-left"></i> <cfif local.isEs>Intercambiar<cfelse>Swap</cfif></button><button type="button" class="tool-copy" data-copy-target="cfml-converter-output"><i class="far fa-copy"></i> <cfif local.isEs>Copiar resultado<cfelse>Copy result</cfif></button><button type="button" class="tool-copy" id="cfml-converter-clear"><i class="fas fa-eraser"></i> <cfif local.isEs>Limpiar<cfelse>Clear</cfif></button></div>
  <p class="tool-message" id="cfml-converter-message" aria-live="polite"></p>
</div>
<script>
(function(){var input=document.getElementById('cfml-converter-input'),output=document.getElementById('cfml-converter-output'),direction=document.getElementById('cfml-converter-direction'),indent=document.getElementById('cfml-converter-indent'),message=document.getElementById('cfml-converter-message'),es=<cfif local.isEs>true<cfelse>false</cfif>,lt=String.fromCharCode(60),gt=String.fromCharCode(62);
function pad(level){var unit=indent.value==='tab'?'\t':Array(Number(indent.value)+1).join(' ');return Array(level+1).join(unit);}
function tag(name){return lt+name+gt;}
function tagToScript(code){var out=[],level=0;code.replace(/\r\n/g,'\n').split('\n').forEach(function(raw){var line=raw.trim(),m;if(!line){out.push('');return;}m=line.match(new RegExp('^'+lt+'cfset\\s+([\\s\\S]*?)\\s*'+gt+'$','i'));if(m){out.push(pad(level)+m[1].replace(/;?$/,';'));return;}m=line.match(new RegExp('^'+lt+'cfoutput\\s*'+gt+'([\\s\\S]*?)'+lt+'/cfoutput'+gt+'$','i'));if(m){var value=m[1].trim();out.push(pad(level)+(value.charAt(0)==='#'&&value.charAt(value.length-1)==='#'?'writeOutput('+value.slice(1,-1)+');':'writeOutput("'+value.replace(/\\/g,'\\\\').replace(/"/g,'\\"')+'");'));return;}m=line.match(new RegExp('^'+lt+'cfif\\s+([\\s\\S]*?)'+gt+'$','i'));if(m){out.push(pad(level)+'if ('+m[1].trim()+') {');level++;return;}m=line.match(new RegExp('^'+lt+'cfelseif\\s+([\\s\\S]*?)'+gt+'$','i'));if(m){level=Math.max(0,level-1);out.push(pad(level)+'} else if ('+m[1].trim()+') {');level++;return;}if(new RegExp('^'+lt+'cfelse\\s*'+gt+'$','i').test(line)){level=Math.max(0,level-1);out.push(pad(level)+'} else {');level++;return;}if(new RegExp('^'+lt+'/cfif'+gt+'$','i').test(line)){level=Math.max(0,level-1);out.push(pad(level)+'}');return;}m=line.match(new RegExp('^'+lt+'cfloop\\s+query="([^"]+)"'+gt+'$','i'));if(m){out.push(pad(level)+'for (var row in '+m[1]+') {');level++;return;}if(new RegExp('^'+lt+'/cfloop'+gt+'$','i').test(line)){level=Math.max(0,level-1);out.push(pad(level)+'}');return;}out.push(pad(level)+line);});return out.join('\n');}
function scriptToTag(code){var out=[],level=0;code.replace(/\r\n/g,'\n').split('\n').forEach(function(raw){var line=raw.trim(),m;if(!line){out.push('');return;}m=line.match(/^if\s*\((.*)\)\s*\{$/);if(m){out.push(pad(level)+tag('cfif '+m[1]));level++;return;}m=line.match(/^\}\s*else\s+if\s*\((.*)\)\s*\{$/);if(m){level=Math.max(0,level-1);out.push(pad(level)+tag('cfelseif '+m[1]));level++;return;}if(/^\}\s*else\s*\{$/.test(line)){level=Math.max(0,level-1);out.push(pad(level)+tag('cfelse'));level++;return;}if(line==='}'||line==='};'){level=Math.max(0,level-1);out.push(pad(level)+tag('/cfif'));return;}m=line.match(/^writeOutput\((.*)\);?$/);if(m){var expr=m[1].trim();out.push(pad(level)+tag('cfoutput')+(expr.charAt(0)==='"'&&expr.charAt(expr.length-1)==='"'?expr.slice(1,-1):'#'+expr+'#')+tag('/cfoutput'));return;}m=line.match(/^(.+?);$/);if(m){out.push(pad(level)+tag('cfset '+m[1]));return;}out.push(pad(level)+line);});return out.join('\n');}
function convert(){if(!input.value.trim()){output.value='';message.textContent=es?'Pegá código CFML para convertir.':'Paste CFML code to convert.';message.className='tool-message is-error';return;}output.value=direction.value==='tag-script'?tagToScript(input.value):scriptToTag(input.value);message.textContent=es?'Código convertido. Revisá manualmente las partes complejas antes de usarlo.':'Code converted. Review complex sections manually before using it.';message.className='tool-message';}
direction.addEventListener('change',function(){if(input.value.trim())convert();});indent.addEventListener('change',function(){if(input.value.trim())convert();});document.getElementById('cfml-converter-convert').addEventListener('click',convert);document.getElementById('cfml-converter-swap').addEventListener('click',function(){var old=input.value;input.value=output.value;output.value=old;direction.value=direction.value==='tag-script'?'script-tag':'tag-script';if(input.value.trim())convert();});document.getElementById('cfml-converter-clear').addEventListener('click',function(){input.value='';output.value='';message.textContent='';});}());
</script>
