<div class="tool-widget widget-cfml-code-doctor">
  <label for="cfml-code-doctor-input"><cfif local.isEs>Código CFML o consulta SQL<cfelse>CFML code or SQL query</cfif></label>
  <textarea id="cfml-code-doctor-input" rows="14" spellcheck="false" placeholder='<cfif local.isEs>&lt;cfquery name="qUsers"&gt;SELECT * FROM users&lt;/cfquery&gt;<cfelse>&lt;cfquery name="qUsers"&gt;SELECT * FROM users&lt;/cfquery&gt;</cfif>'></textarea>
  <div class="cfml-doctor-preview-label"><i class="fas fa-list-ol"></i> <cfif local.isEs>Vista numerada — los números no se copian<cfelse>Numbered view — line numbers are not copied</cfif></div>
  <pre id="cfml-code-doctor-preview" class="cfml-doctor-code-preview" aria-label="Numbered code preview"></pre>
  <div class="widget-buttons">
    <button type="button" class="btn-social btn-upwork" id="cfml-code-doctor-scan"><i class="fas fa-stethoscope"></i> <cfif local.isEs>Analizar código<cfelse>Scan code</cfif></button>
    <button type="button" class="tool-copy" data-copy-target="cfml-code-doctor-input"><i class="far fa-copy"></i> <cfif local.isEs>Copiar entrada<cfelse>Copy input</cfif></button>
  </div>
  <p class="tool-message" id="cfml-code-doctor-message" aria-live="polite"></p>
  <div id="cfml-code-doctor-results" class="cfml-doctor-results"></div>
</div>
<script>
(function(){
  var input=document.getElementById('cfml-code-doctor-input'), preview=document.getElementById('cfml-code-doctor-preview'), message=document.getElementById('cfml-code-doctor-message'), results=document.getElementById('cfml-code-doctor-results');
  var es=<cfif local.isEs>true<cfelse>false</cfif>;
  var lt=String.fromCharCode(60), rules=[
    {re:new RegExp(lt+'cfquery\\b(?![^>]*\\bdbtype\\b)[^>]*>[\\s\\S]*?'+lt+'/cfquery>','i'),level:'warning',title:es?'Revisá la consulta':'Review the query',detail:es?'Asegurate de usar cfqueryparam en todos los valores dinámicos.':'Make sure every dynamic value uses cfqueryparam.'},
    {re:/\bselect\s+\*\s+from\b/i,level:'warning',title:'SELECT *',detail:es?'Indicá las columnas necesarias para reducir datos y acoplamiento.':'List the required columns to reduce data and coupling.'},
    {re:new RegExp(lt+'cfloop\\b[^>]*>[\\s\\S]*?'+lt+'cfquery\\b','i'),level:'danger',title:es?'Consulta dentro de un loop':'Query inside a loop',detail:es?'Evitá ejecutar una consulta por cada elemento; buscá una consulta agrupada.':'Avoid running one query per item; look for a batched query.'},
    {re:/\b(?:url|form|cgi|cookie|session|application)\.[A-Za-z_][\w]*/i,level:'info',title:es?'Variable de scope externo':'External scope variable',detail:es?'Validá y/o asigná este valor a una variable local antes de usarlo.':'Validate and/or copy this value to a local variable before using it.'},
    {re:/(?:^|[^.\w])(?:count|name|result|data|query)\s*=/im,level:'info',title:es?'Variable posiblemente sin scope':'Possibly unscoped variable',detail:es?'Preferí local.nombre o variables.nombre para evitar colisiones.':'Prefer local.name or variables.name to avoid collisions.'},
    {re:/\b(?:password|secret|token|api[_-]?key)\s*=\s*["'][^"']+["']/i,level:'danger',title:es?'Secreto expuesto':'Exposed secret',detail:es?'No guardes credenciales en el código fuente; usá variables de entorno o configuración segura.':'Do not keep credentials in source; use environment variables or secure configuration.'},
    {re:new RegExp(lt+'cfquery\\b[^>]*>(?![\\s\\S]*?'+lt+'cfqueryparam\\b)[\\s\\S]*?#(?:url|form|cgi|cookie|session|application)\\.[\\s\\S]*?'+lt+'/cfquery>','i'),level:'danger',title:es?'SQL dinámico sin protección':'Unprotected dynamic SQL',detail:es?'Usá cfqueryparam para todos los valores externos dentro de la consulta.':'Use cfqueryparam for every external value inside the query.'},
    {re:/\bevaluate\s*\(/i,level:'danger',title:es?'Evaluate detectado':'Evaluate detected',detail:es?'Evitá evaluar texto como código; buscá una alternativa explícita y segura.':'Avoid evaluating text as code; use an explicit and safer alternative.'},
    {re:new RegExp(lt+'cfexecute\\b','i'),level:'danger',title:es?'Ejecución de comando externo':'External command execution',detail:es?'Validá estrictamente los argumentos y evitá construir comandos con datos del usuario.':'Strictly validate arguments and never build commands from user input.'},
    {re:/\bqueryExecute\s*\([^;\n]*\)(?!\s*;)/i,level:'warning',title:es?'Revisá queryExecute':'Review queryExecute',detail:es?'Preferí pasar parámetros y opciones explícitas para evitar SQL dinámico inseguro.':'Pass explicit parameters and options to avoid unsafe dynamic SQL.'},
    {re:new RegExp(lt+'cfinclude\\b[^>]*#(?:url|form|cgi)\\.','i'),level:'warning',title:es?'Include dinámico':'Dynamic include',detail:es?'No armes rutas de include directamente con datos externos; usá una lista permitida.':'Do not build include paths directly from external data; use an allowlist.'}
  ];
  function escapeHtml(value){return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function updatePreview(findings){var lines=input.value.replace(/\r\n/g,'\n').split('\n'),lineLevels={};(findings||[]).forEach(function(item){if(!lineLevels[item.line]||item.level==='danger'||(item.level==='warning'&&lineLevels[item.line]==='info'))lineLevels[item.line]=item.level;});preview.innerHTML=lines.map(function(line,index){var level=lineLevels[index+1]||'';return '<span class="cfml-doctor-code-line"><span class="cfml-doctor-line-number '+level+'">'+(index+1)+'</span><span class="cfml-doctor-line-content">'+(escapeHtml(line)||' ')+'</span></span>';}).join('');}
  function fixSuggestion(item){var title=item.title.toLowerCase();if(title.indexOf('sql dinámico')>=0||title.indexOf('unprotected dynamic')>=0)return es?'Usá cfqueryparam con value y cfsqltype en cada valor externo.':'Use cfqueryparam with value and cfsqltype for every external value.';if(title.indexOf('select *')>=0)return es?'Reemplazá SELECT * por una lista explícita de columnas.':'Replace SELECT * with an explicit column list.';if(title.indexOf('scope')>=0)return es?'Asigná el valor a local.nombre o variables.nombre antes de usarlo.':'Assign the value to local.name or variables.name before using it.';if(title.indexOf('loop')>=0||title.indexOf('consulta dentro')>=0)return es?'Mové la consulta fuera del loop o convertí el proceso en una consulta agrupada.':'Move the query outside the loop or batch the operation.';if(title.indexOf('evaluate')>=0)return es?'Reemplazá evaluate() por una función explícita o una estructura de control segura.':'Replace evaluate() with an explicit function or safe control structure.';if(title.indexOf('secreto')>=0||title.indexOf('secret')>=0)return es?'Leé el secreto desde variables de entorno o configuración segura.':'Read the secret from environment variables or secure configuration.';if(title.indexOf('include')>=0)return es?'Usá una lista permitida de rutas para evitar includes dinámicos.':'Use an allowlist of paths to avoid dynamic includes.';return es?'Revisá este patrón y aplicá una alternativa explícita.':'Review this pattern and use an explicit alternative.';}
  function scan(){var code=input.value,found=[]; results.innerHTML=''; if(!code.trim()){updatePreview();message.textContent=es?'Pegá código para analizar.':'Paste code to scan.'; message.className='tool-message is-error'; return;} rules.forEach(function(rule){var match=rule.re.exec(code); if(match){var before=code.slice(0,match.index),lastBreak=before.lastIndexOf('\n'),lineStart=lastBreak+1,lineEnd=code.indexOf('\n',match.index);rule.line=before.split(/\r?\n/).length;rule.column=match.index-(lastBreak+1)+1;rule.fragment=code.slice(lineStart,lineEnd<0?code.length:lineEnd).trim();found.push(rule);}}); updatePreview(found); message.textContent=es?(found.length?'Se encontraron '+found.length+' observaciones.':'No se encontraron patrones en esta revisión rápida.'):(found.length?found.length+' finding(s) detected.':'No patterns found in this quick review.'); message.className='tool-message'; if(!found.length)return; results.innerHTML=found.map(function(item){var location=(es?'Línea ':'Line ')+item.line+(es?' · columna ':' · column ')+item.column;return '<div class="cfml-doctor-result '+item.level+'"><strong>'+item.title+'</strong><span class="cfml-doctor-location"><i class="fas fa-location-arrow"></i> '+location+'</span><code class="cfml-doctor-fragment">'+escapeHtml(item.fragment||'')+'</code><p>'+item.detail+'</p><p class="cfml-doctor-fix"><strong>'+ (es?'Sugerencia:':'Suggestion:')+'</strong> '+fixSuggestion(item)+'</p></div>';}).join('');}
  input.addEventListener('input',function(){updatePreview();}); updatePreview();
  document.getElementById('cfml-code-doctor-scan').addEventListener('click',scan);
}());
</script>
