<div class="tool-widget widget-cfml-hosting-migration-calculator">
  <div class="hosting-calc-grid"><div><label for="hosting-sites"><cfif local.isEs>Sitios o aplicaciones<cfelse>Sites or applications</cfif></label><input id="hosting-sites" type="number" value="1" min="1"></div><div><label for="hosting-traffic"><cfif local.isEs>Tráfico mensual (GB)<cfelse>Monthly traffic (GB)</cfif></label><input id="hosting-traffic" type="number" value="100" min="1"></div><div><label for="hosting-database"><cfif local.isEs>Base de datos (GB)<cfelse>Database size (GB)</cfif></label><input id="hosting-database" type="number" value="5" min="0"></div><div><label for="hosting-storage"><cfif local.isEs>Archivos y backups (GB)<cfelse>Files and backups (GB)</cfif></label><input id="hosting-storage" type="number" value="20" min="1"></div><div><label for="hosting-instances"><cfif local.isEs>Instancias CFML<cfelse>CFML instances</cfif></label><input id="hosting-instances" type="number" value="1" min="1"></div><div><label for="hosting-provider"><cfif local.isEs>Infraestructura objetivo<cfelse>Target infrastructure</cfif></label><select id="hosting-provider"><option value="vps">VPS administrado</option><option value="aws">AWS / cloud</option><option value="dedicated">Servidor dedicado</option></select></div></div>
  <div class="widget-buttons"><button type="button" class="btn-social btn-upwork" id="hosting-calculate"><i class="fas fa-calculator"></i> <cfif local.isEs>Estimar infraestructura<cfelse>Estimate infrastructure</cfif></button></div><p class="tool-message" id="hosting-message" aria-live="polite"></p><div id="hosting-results" class="hosting-results"></div><div class="hosting-checklist"><h3><i class="fas fa-list-check"></i> <cfif local.isEs>Checklist de migración<cfelse>Migration checklist</cfif></h3><ul id="hosting-checklist-items"></ul></div>
</div>
<script>
(function(){var sites=document.getElementById('hosting-sites'),traffic=document.getElementById('hosting-traffic'),database=document.getElementById('hosting-database'),storage=document.getElementById('hosting-storage'),instances=document.getElementById('hosting-instances'),provider=document.getElementById('hosting-provider'),results=document.getElementById('hosting-results'),items=document.getElementById('hosting-checklist-items'),message=document.getElementById('hosting-message'),es=<cfif local.isEs>true<cfelse>false</cfif>;
function calculate(){var s=Math.max(1,Number(sites.value)||1),t=Math.max(1,Number(traffic.value)||1),db=Math.max(0,Number(database.value)||0),files=Math.max(1,Number(storage.value)||1),count=Math.max(1,Number(instances.value)||1),cpu=Math.max(2,Math.ceil(1+s*.35+t/250+count*.4)),ram=Math.max(4,Math.ceil(2+s*.65+db*.12+count*.8)),disk=Math.max(40,Math.ceil(files*1.5+db+20)),cost=provider.value==='aws'?Math.ceil(35+ram*7+disk*.08):provider.value==='dedicated'?Math.ceil(160+ram*5+disk*.04):Math.ceil(25+ram*4+disk*.05),label=provider.value==='aws'?'AWS / cloud':provider.value==='dedicated'?(es?'Servidor dedicado':'Dedicated server'):(es?'VPS administrado':'Managed VPS'),recommend=ram>=16?(es?'Servidor dedicado o cloud escalable':'Dedicated or scalable cloud'):ram>=8?(es?'VPS de 8–16 GB o cloud equivalente':'8–16 GB VPS or equivalent cloud'):(es?'VPS de 4–8 GB':'4–8 GB VPS');results.innerHTML='<div class="hosting-result-card"><strong>CPU</strong><span>'+cpu+' vCPU</span></div><div class="hosting-result-card highlight"><strong>RAM</strong><span>'+ram+' GB</span></div><div class="hosting-result-card"><strong>Disco</strong><span>'+disk+' GB SSD</span></div><div class="hosting-result-card"><strong>'+ (es?'Estimación mensual':'Monthly estimate')+'</strong><span>USD '+cost+'</span></div><div class="hosting-summary"><strong>'+label+'</strong><p>'+recommend+'</p></div>';var list=es?['Inventariar aplicaciones, datasources y tareas programadas.','Respaldar archivos, bases de datos y configuración.','Preparar DNS, SSL, variables de entorno y accesos.','Probar la aplicación en staging antes del cambio.','Definir ventana de migración y plan de rollback.']:['Inventory applications, datasources, and scheduled tasks.','Back up files, databases, and configuration.','Prepare DNS, SSL, environment variables, and access.','Test the application in staging before cutover.','Define a migration window and rollback plan.'];items.innerHTML=list.map(function(item){return '<li><i class="fas fa-check"></i>'+item+'</li>';}).join('');message.textContent=es?'Estimación orientativa. Validá consumos y precios reales con tu proveedor.':'Planning estimate. Validate real usage and pricing with your provider.';message.className='tool-message';}
document.getElementById('hosting-calculate').addEventListener('click',calculate);calculate();}());
</script>
