<div class="tool-widget widget-commandbox-server-json-generator">
  <div class="commandbox-form-grid"><div><label for="commandbox-engine"><cfif local.isEs>Motor CFML<cfelse>CFML engine</cfif></label><select id="commandbox-engine"><option value="lucee">Lucee</option><option value="adobe">Adobe ColdFusion</option></select></div><div><label for="commandbox-version"><cfif local.isEs>Versión del motor<cfelse>Engine version</cfif></label><input id="commandbox-version" value="6.1.0" placeholder="6.1.0" /></div><div><label for="commandbox-port">HTTP port</label><input id="commandbox-port" type="number" value="8500" min="1" max="65535"></div><div><label for="commandbox-hostname">Hostname</label><input id="commandbox-hostname" value="127.0.0.1"></div><div><label for="commandbox-ssl"><cfif local.isEs>¿Habilitar SSL?<cfelse>Enable SSL?</cfif></label><select id="commandbox-ssl"><option value="false">No</option><option value="true">Sí</option></select></div><div><label for="commandbox-ssl-port">SSL port</label><input id="commandbox-ssl-port" type="number" value="8443" min="1" max="65535"></div><div><label for="commandbox-jvm-min">JVM min memory</label><input id="commandbox-jvm-min" value="512m"></div><div><label for="commandbox-jvm-max">JVM max memory</label><input id="commandbox-jvm-max" value="2048m"></div></div>
  <div class="commandbox-wide-fields"><label for="commandbox-datasource"><cfif local.isEs>Datasource (nombre=URL JDBC)<cfelse>Datasource (name=JDBC URL)</cfif></label><textarea id="commandbox-datasource" rows="3" placeholder="myApp=jdbc:mysql://localhost/myapp"></textarea><label for="commandbox-extensions"><cfif local.isEs>Extensiones (una por línea)<cfelse>Extensions (one per line)</cfif></label><textarea id="commandbox-extensions" rows="3" placeholder="lucee.extension:pdf&#10;lucee.extension:redis"></textarea><label for="commandbox-install"><cfif local.isEs>Scripts de instalación (uno por línea)<cfelse>Install scripts (one per line)</cfif></label><textarea id="commandbox-install" rows="3" placeholder="install commandbox-dotenv"></textarea></div>
  <div class="widget-buttons"><button type="button" class="btn-social btn-upwork" id="commandbox-generate"><i class="fas fa-wand-magic-sparkles"></i> <cfif local.isEs>Generar server.json<cfelse>Generate server.json</cfif></button><button type="button" class="tool-copy" data-copy-target="commandbox-output"><i class="far fa-copy"></i> <cfif local.isEs>Copiar JSON<cfelse>Copy JSON</cfif></button><button type="button" class="tool-copy" id="commandbox-download"><i class="fas fa-download"></i> <cfif local.isEs>Descargar JSON<cfelse>Download JSON</cfif></button></div>
  <p class="tool-message" id="commandbox-message" aria-live="polite"></p><label for="commandbox-output"><cfif local.isEs>server.json generado<cfelse>Generated server.json</cfif></label><textarea id="commandbox-output" rows="22" readonly spellcheck="false"></textarea>
</div>
<script>
(function(){var engine=document.getElementById('commandbox-engine'),version=document.getElementById('commandbox-version'),port=document.getElementById('commandbox-port'),host=document.getElementById('commandbox-hostname'),ssl=document.getElementById('commandbox-ssl'),sslPort=document.getElementById('commandbox-ssl-port'),jvmMin=document.getElementById('commandbox-jvm-min'),jvmMax=document.getElementById('commandbox-jvm-max'),datasource=document.getElementById('commandbox-datasource'),extensions=document.getElementById('commandbox-extensions'),install=document.getElementById('commandbox-install'),output=document.getElementById('commandbox-output'),message=document.getElementById('commandbox-message'),es=<cfif local.isEs>true<cfelse>false</cfif>;
function lines(value){return value.split(/\r?\n/).map(function(v){return v.trim();}).filter(Boolean);}
function generate(){var server={app:{cfengine:engine.value+'@'+version.value.trim()},web:{http:{port:Number(port.value)||8500,host:host.value.trim()||'127.0.0.1'}},jvm:{heapSizeMin:jvmMin.value.trim()||'512m',heapSizeMax:jvmMax.value.trim()||'2048m'}};if(ssl.value==='true')server.web.ssl={port:Number(sslPort.value)||8443};var ds={};lines(datasource.value).forEach(function(row){var p=row.split('=');if(p[0]&&p.slice(1).join('='))ds[p[0].trim()]={url:p.slice(1).join('=').trim()};});if(Object.keys(ds).length)server.datasources=ds;var ext=lines(extensions.value);if(ext.length)server.app.extensions=ext;var scripts=lines(install.value);if(scripts.length)server.actions={onCreate:scripts};output.value=JSON.stringify(server,null,4);message.textContent=es?'server.json generado. Revisá rutas, credenciales y puertos antes de desplegar.':'server.json generated. Review paths, credentials, and ports before deploying.';message.className='tool-message';}
document.getElementById('commandbox-generate').addEventListener('click',generate);document.getElementById('commandbox-download').addEventListener('click',function(){if(!output.value)generate();var link=document.createElement('a');link.href=URL.createObjectURL(new Blob([output.value],{type:'application/json'}));link.download='server.json';link.click();URL.revokeObjectURL(link.href);});}());
</script>
