<div class="tool-widget widget-csv-table-generator">
  <label for="csv-input"><cfif local.isEs>Datos CSV<cfelse>CSV data</cfif></label>
  <textarea id="csv-input" rows="12" spellcheck="false" placeholder='<cfif local.isEs>Nombre,Email,Estado<br>Ana,ana@ejemplo.com,Activo<br>Juan,juan@ejemplo.com,Inactivo<cfelse>Name,Email,Status<br>Ana,ana@example.com,Active<br>John,john@example.com,Inactive</cfif>'></textarea>
  <div class="csv-options"><label for="csv-delimiter"><cfif local.isEs>Separador<cfelse>Separator</cfif></label><select id="csv-delimiter"><option value="auto"><cfif local.isEs>Detectar automáticamente<cfelse>Auto-detect</cfif></option><option value=",">, <cfif local.isEs>(coma)<cfelse>(comma)</cfif></option><option value=";">; <cfif local.isEs>(punto y coma)<cfelse>(semicolon)</cfif></option><option value="\t">Tab</option><option value="|">| <cfif local.isEs>(barra vertical)<cfelse>(pipe)</cfif></option></select><label class="csv-check"><input type="checkbox" id="csv-headers" checked> <cfif local.isEs>La primera fila es encabezado<cfelse>First row is header</cfif></label></div>
  <div class="widget-buttons"><button type="button" class="btn-social btn-upwork" id="csv-generate"><i class="fas fa-table"></i> <cfif local.isEs>Generar tablas<cfelse>Generate tables</cfif></button><button type="button" class="tool-copy" id="csv-copy-markdown"><i class="far fa-copy"></i> Markdown</button><button type="button" class="tool-copy" id="csv-copy-html"><i class="far fa-copy"></i> HTML</button><button type="button" class="tool-copy" id="csv-download"><i class="fas fa-download"></i> <cfif local.isEs>Descargar HTML<cfelse>Download HTML</cfif></button></div>
  <p class="tool-message" id="csv-message" aria-live="polite"></p><div class="csv-preview-wrap"><h3><cfif local.isEs>Vista previa<cfelse>Preview</cfif></h3><div id="csv-preview" class="csv-preview"></div></div>
  <div class="csv-output-grid"><div><label for="csv-markdown"><cfif local.isEs>Resultado Markdown<cfelse>Markdown result</cfif></label><textarea id="csv-markdown" rows="10" readonly spellcheck="false"></textarea></div><div><label for="csv-html"><cfif local.isEs>Resultado HTML<cfelse>HTML result</cfif></label><textarea id="csv-html" rows="10" readonly spellcheck="false"></textarea></div></div>
</div>
<script>
(function(){var input=document.getElementById('csv-input'),delimiter=document.getElementById('csv-delimiter'),headers=document.getElementById('csv-headers'),preview=document.getElementById('csv-preview'),markdown=document.getElementById('csv-markdown'),html=document.getElementById('csv-html'),message=document.getElementById('csv-message'),es=<cfif local.isEs>true<cfelse>false</cfif>,lastHtml='';
function escapeHtml(value){return String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}function keySep(sep){return sep==='\t'?'t':sep;}function parseCsv(text,sep){var rows=[],row=[],cell='',quoted=false;for(var i=0;i<text.length;i++){var ch=text[i],next=text[i+1];if(ch==='"'&&quoted&&next==='"'){cell+='"';i++;}else if(ch==='"'){quoted=!quoted;}else if(ch===sep&&!quoted){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell);if(row.some(function(v){return v!=='';}))rows.push(row);row=[];cell='';}else cell+=ch;}if(cell!==''||row.length){row.push(cell);if(row.some(function(v){return v!=='';}))rows.push(row);}return rows;}function detect(text){var first=text.split(/\r?\n/)[0]||'',options=[',',';','\t','|'];return options.reduce(function(best,sep){var count=first.split(sep).length-1;return count>best.count?{sep:sep,count:count}:best;},{sep:',',count:-1}).sep;}
function makeMarkdown(rows,useHeaders){var data=rows.map(function(row){return row.map(function(cell){return String(cell).replace(/\|/g,'\\|').replace(/\r?\n/g,' ');});}),width=Math.max.apply(null,data.map(function(r){return r.length;}));data.forEach(function(r){while(r.length<width)r.push('');});var lines=[];if(useHeaders){lines.push('| '+data[0].join(' | ')+' |');lines.push('| '+data[0].map(function(){return '---';}).join(' | ')+' |');data.slice(1).forEach(function(r){lines.push('| '+r.join(' | ')+' |');});}else data.forEach(function(r){lines.push('| '+r.join(' | ')+' |');});return lines.join('\n');}function makeHtml(rows,useHeaders){var body=rows.map(function(row,index){return '<tr>'+row.map(function(cell){var cellTag=useHeaders&&index===0?'th':'td';return '<'+cellTag+'>'+escapeHtml(cell)+'</'+cellTag+'>';}).join('')+'</tr>';}).join('');return '<table>\n  <tbody>\n    '+body.replace(/<tr>/g,'<tr>\n      ').replace(/<\/tr>/g,'\n    </tr>')+'\n  </tbody>\n</table>';}
function generate(){var text=input.value.trim();if(!text){message.textContent=es?'Pegá datos CSV para comenzar.':'Paste CSV data to begin.';message.className='tool-message is-error';return;}var sep=delimiter.value==='auto'?detect(text):delimiter.value;if(sep==='\\t')sep='\t';var rows=parseCsv(text,sep);if(!rows.length){message.textContent=es?'No se encontraron filas válidas.':'No valid rows found.';message.className='tool-message is-error';return;}markdown.value=makeMarkdown(rows,headers.checked);lastHtml=makeHtml(rows,headers.checked);html.value=lastHtml;preview.innerHTML=lastHtml;message.textContent=(es?'Filas procesadas: ':'Rows processed: ')+rows.length+(es?' · Separador: ':' · Separator: ')+(sep==='\t'?'Tab':sep);message.className='tool-message';}
function copy(value){if(!value){message.textContent=es?'Primero generá la tabla.':'Generate the table first.';message.className='tool-message is-error';return;}var done=false;if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(value).then(function(){showCopied();}).catch(function(){fallbackCopy(value);});}else fallbackCopy(value);}function fallbackCopy(value){var temp=document.createElement('textarea');temp.value=value;temp.style.position='fixed';temp.style.opacity='0';document.body.appendChild(temp);temp.focus();temp.select();try{document.execCommand('copy');showCopied();}catch(e){message.textContent=es?'Seleccioná y copiá el resultado manualmente.':'Select and copy the result manually.';message.className='tool-message is-error';}document.body.removeChild(temp);}function showCopied(){message.textContent=es?'Copiado al portapapeles.':'Copied to clipboard.';message.className='tool-message';}
document.getElementById('csv-generate').addEventListener('click',generate);document.getElementById('csv-copy-markdown').addEventListener('click',function(){copy(markdown.value);});document.getElementById('csv-copy-html').addEventListener('click',function(){copy(html.value);});document.getElementById('csv-download').addEventListener('click',function(){if(!lastHtml)generate();if(!lastHtml)return;var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lastHtml],{type:'text/html'}));a.download='tabla.html';a.click();URL.revokeObjectURL(a.href);});}());
</script>
