<div class="tool-widget widget-currency-converter">
  <label for="currency-amount"><cfif local.isEs>Importe<cfelse>Amount</cfif></label><input id="currency-amount" type="number" min="0" step="any" value="1">
  <label for="currency-from"><cfif local.isEs>De<cfelse>From</cfif></label><select id="currency-from"></select>
  <label for="currency-to"><cfif local.isEs>A<cfelse>To</cfif></label><select id="currency-to"></select>
  <button type="button" class="btn-social btn-upwork" id="currency-run"><i class="fas fa-coins"></i> <cfif local.isEs>Convertir<cfelse>Convert</cfif></button>
  <p class="tool-message" id="currency-result" aria-live="polite"></p><small><cfif local.isEs>Las tasas se consultan en tiempo real desde una API pública gratuita y pueden no coincidir con la cotización de tu banco o casa de cambio.<cfelse>Rates are fetched live from a free public API and may differ from your bank or exchange provider.</cfif></small>
</div>
<script>
(function(){var codes=['ARS','AUD','BRL','CAD','CHF','CLP','CNY','COP','EUR','GBP','JPY','MXN','USD','UYU'];var from=document.getElementById('currency-from'),to=document.getElementById('currency-to');codes.forEach(function(c){from.add(new Option(c,c));to.add(new Option(c,c));});from.value='USD';to.value='ARS';document.getElementById('currency-run').addEventListener('click',function(){var amount=Number(document.getElementById('currency-amount').value),result=document.getElementById('currency-result');if(!isFinite(amount)){result.className='tool-message is-error';result.textContent='<cfif local.isEs>Ingresá un importe válido.<cfelse>Enter a valid amount.</cfif>';return;}result.className='tool-message';result.textContent='<cfif local.isEs>Consultando tasa…<cfelse>Fetching rate…</cfif>';fetch('https://open.er-api.com/v6/latest/'+encodeURIComponent(from.value)).then(function(r){if(!r.ok)throw new Error();return r.json();}).then(function(d){if(d.result!=='success'||!d.rates[to.value])throw new Error();var value=amount*d.rates[to.value];result.textContent=amount.toLocaleString()+' '+from.value+' = '+value.toLocaleString('<cfif local.isEs>es-AR<cfelse>en-US</cfif>',{maximumFractionDigits:2})+' '+to.value+' · 1 '+from.value+' = '+d.rates[to.value]+' '+to.value;}).catch(function(){result.className='tool-message is-error';result.textContent='<cfif local.isEs>No se pudo obtener la tasa actual. Intentá más tarde.<cfelse>Could not get the current rate. Please try again later.</cfif>';});});}());
</script>
