<div class="tool-widget widget-json-yaml-converter">
  <label for="json-yaml-input"><cfif local.isEs>JSON o YAML de entrada<cfelse>Input JSON or YAML</cfif></label><textarea id="json-yaml-input" rows="10" spellcheck="false"></textarea>
  <div class="widget-buttons"><button type="button" class="btn-social btn-upwork" data-yaml-action="to-yaml">JSON → YAML</button><button type="button" class="btn-social btn-upwork" data-yaml-action="to-json">YAML → JSON</button></div><p class="tool-message" id="json-yaml-message" aria-live="polite"></p>
  <label for="json-yaml-output"><cfif local.isEs>Resultado<cfelse>Result</cfif></label><textarea id="json-yaml-output" rows="10" readonly spellcheck="false"></textarea><button type="button" class="tool-copy" data-copy-target="json-yaml-output"><i class="far fa-copy"></i> <cfif local.isEs>Copiar<cfelse>Copy</cfif></button>
  <small><cfif local.isEs>Admite YAML básico (mapas, listas y valores escalares).<cfelse>Supports basic YAML (maps, lists, and scalar values).</cfif></small>
</div>
<script>
(function(){var i=document.getElementById('json-yaml-input'),o=document.getElementById('json-yaml-output'),m=document.getElementById('json-yaml-message');function scalar(v){v=v.trim();if(/^['"].*['"]$/.test(v))return v.slice(1,-1);if(v==='true'||v==='false')return v==='true';if(v==='null')return null;if(v!==''&&!isNaN(v))return Number(v);return v;}function yaml(obj,n){n=n||'';if(Array.isArray(obj))return obj.map(function(v){return n+'- '+(typeof v==='object'?'\n'+yaml(v,n+'  '):String(v));}).join('\n');return Object.keys(obj).map(function(k){var v=obj[k];return n+k+':'+(v&&typeof v==='object'?'\n'+yaml(v,n+'  '):' '+String(v));}).join('\n');}function parse(s){var root={},stack=[{indent:-1,obj:root}];s.split(/\r?\n/).forEach(function(line){if(!line.trim()||/^\s*#/.test(line))return;var indent=line.match(/^\s*/)[0].length, text=line.trim();while(stack.length>1&&indent<=stack[stack.length-1].indent)stack.pop();var parent=stack[stack.length-1].obj;if(text.indexOf('- ')===0){if(!Array.isArray(parent))throw Error('Invalid list');parent.push(scalar(text.slice(2)));return;}var p=text.indexOf(':');if(p<0)throw Error('Invalid YAML line');var k=text.slice(0,p).trim(),v=text.slice(p+1).trim();if(v===''){parent[k]={};stack.push({indent:indent,obj:parent[k]});}else parent[k]=scalar(v);});return root;}document.querySelectorAll('[data-yaml-action]').forEach(function(b){b.addEventListener('click',function(){try{o.value=b.dataset.yamlAction==='to-yaml'?yaml(JSON.parse(i.value)):JSON.stringify(parse(i.value),null,2);m.textContent='';m.className='tool-message';}catch(e){m.textContent='<cfif local.isEs>Error de conversión: <cfelse>Conversion error: </cfif>'+e.message;m.className='tool-message is-error';}});});}());
</script>
