<div class="tool-widget widget-json-formatter">
  <label for="json-formatter-input"><cfif local.isEs>JSON de entrada<cfelse>Input JSON</cfif></label>
  <textarea id="json-formatter-input" rows="10" spellcheck="false" placeholder='{"hello":"world"}'></textarea>
  <div class="widget-file-actions"><label class="tool-file-label" for="json-formatter-file"><i class="fas fa-upload"></i> <cfif local.isEs>Subir archivo JSON<cfelse>Upload JSON file</cfif></label><input type="file" id="json-formatter-file" accept=".json,application/json"></div>
  <div class="widget-buttons"><button type="button" class="btn-social btn-upwork" data-json-action="format"><i class="fas fa-align-left"></i> <cfif local.isEs>Formatear<cfelse>Format</cfif></button><button type="button" class="btn-social btn-upwork" data-json-action="minify"><i class="fas fa-compress-alt"></i> <cfif local.isEs>Minificar<cfelse>Minify</cfif></button></div>
  <p class="tool-message" id="json-formatter-message" aria-live="polite"></p>
  <label for="json-formatter-output"><cfif local.isEs>Resultado<cfelse>Result</cfif></label>
  <textarea id="json-formatter-output" rows="8" readonly spellcheck="false"></textarea>
  <button type="button" class="tool-copy" data-copy-target="json-formatter-output"><i class="far fa-copy"></i> <cfif local.isEs>Copiar<cfelse>Copy</cfif></button><button type="button" class="tool-copy" id="json-formatter-download"><i class="fas fa-download"></i> <cfif local.isEs>Descargar JSON<cfelse>Download JSON</cfif></button>
</div>
<script>
(function(){var i=document.getElementById('json-formatter-input'),o=document.getElementById('json-formatter-output'),m=document.getElementById('json-formatter-message'),fileName='data';function errorLocation(error){var match=error.message.match(/position\s+(\d+)/i);if(!match)return '';var position=Number(match[1]),lines=i.value.slice(0,position).split(/\r?\n/);return ' (<cfif local.isEs>línea <cfelse>line </cfif>'+lines.length+', <cfif local.isEs>columna <cfelse>column </cfif>' +(lines[lines.length-1].length+1)+')';}function transform(action){try{var data=JSON.parse(i.value);o.value=JSON.stringify(data,null,action==='format'?2:0);m.textContent='<cfif local.isEs>JSON válido.<cfelse>Valid JSON.</cfif>';m.className='tool-message';}catch(e){o.value='';m.textContent='<cfif local.isEs>Error de JSON: <cfelse>JSON error: </cfif>'+e.message+errorLocation(e);m.className='tool-message is-error';}}document.querySelectorAll('[data-json-action]').forEach(function(b){b.addEventListener('click',function(){transform(b.dataset.jsonAction);});});document.getElementById('json-formatter-file').addEventListener('change',function(){var file=this.files[0];if(!file)return;fileName=file.name.replace(/\.json$/i,'')||'data';var reader=new FileReader();reader.onload=function(){i.value=reader.result;transform('minify');};reader.readAsText(file);});document.getElementById('json-formatter-download').addEventListener('click',function(){if(!o.value)return;var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([o.value],{type:'application/json'}));a.download=fileName+'.min.json';a.click();URL.revokeObjectURL(a.href);});}());
</script>
