<div class="tool-widget widget-jvm-heap-estimator">
  <div class="jvm-estimator-grid"><div><label for="jvm-ram">RAM del servidor (GB)</label><input id="jvm-ram" type="number" value="8" min="1" max="1024"></div><div><label for="jvm-instances"><cfif local.isEs>Instancias CFML<cfelse>CFML instances</cfif></label><input id="jvm-instances" type="number" value="1" min="1" max="32"></div><div><label for="jvm-traffic"><cfif local.isEs>Tráfico estimado<cfelse>Estimated traffic</cfif></label><select id="jvm-traffic"><option value="low"><cfif local.isEs>Bajo<cfelse>Low</cfif></option><option value="medium" selected><cfif local.isEs>Medio<cfelse>Medium</cfif></option><option value="high"><cfif local.isEs>Alto<cfelse>High</cfif></option></select></div><div><label for="jvm-engine"><cfif local.isEs>Motor CFML<cfelse>CFML engine</cfif></label><select id="jvm-engine"><option value="lucee">Lucee</option><option value="adobe">Adobe ColdFusion</option></select></div></div>
  <div class="widget-buttons"><button type="button" class="btn-social btn-upwork" id="jvm-estimate"><i class="fas fa-calculator"></i> <cfif local.isEs>Calcular recomendación<cfelse>Calculate recommendation</cfif></button></div><p class="tool-message" id="jvm-message" aria-live="polite"></p><div id="jvm-results" class="jvm-results"></div><label for="jvm-flags"><cfif local.isEs>Parámetros sugeridos<cfelse>Suggested parameters</cfif></label><textarea id="jvm-flags" rows="6" readonly spellcheck="false"></textarea>
</div>
<script>
(function(){var ram=document.getElementById('jvm-ram'),instances=document.getElementById('jvm-instances'),traffic=document.getElementById('jvm-traffic'),engine=document.getElementById('jvm-engine'),message=document.getElementById('jvm-message'),results=document.getElementById('jvm-results'),flags=document.getElementById('jvm-flags'),es=<cfif local.isEs>true<cfelse>false</cfif>;
function calculate(){var total=Math.max(1,Number(ram.value)||1)*1024,count=Math.max(1,Number(instances.value)||1),reserveRate=traffic.value==='high'?0.3:traffic.value==='low'?0.18:0.24,reserve=Math.round(total*reserveRate),available=Math.max(512,total-reserve),per=Math.max(384,Math.floor(available/count)),xmx=Math.max(256,Math.floor(per*.72)),xms=Math.max(256,Math.floor(xmx*.5)),meta=traffic.value==='high'?384:256;results.innerHTML='<div class="jvm-result-card"><strong>RAM servidor</strong><span>'+Math.round(total/1024)+' GB</span></div><div class="jvm-result-card"><strong>'+ (es?'Reserva SO y servicios':'OS and services reserve')+'</strong><span>'+reserve+' MB</span></div><div class="jvm-result-card highlight"><strong>-Xmx por instancia</strong><span>'+xmx+' MB</span></div><div class="jvm-result-card"><strong>-Xms por instancia</strong><span>'+xms+' MB</span></div><div class="jvm-result-card"><strong>Metaspace sugerido</strong><span>'+meta+' MB</span></div>';flags.value='-Xms'+xms+'m\n-Xmx'+xmx+'m\n-XX:MaxMetaspaceSize='+meta+'m\n\n# '+engine.value+' · '+count+' '+(es?'instancia(s)':'instance(s)');message.textContent=es?'Estimación inicial calculada. Medí el uso real y ajustá con métricas de producción.':'Initial estimate calculated. Measure real usage and tune it with production metrics.';message.className='tool-message';}
document.getElementById('jvm-estimate').addEventListener('click',calculate);calculate();}());
</script>
