<div class="tool-widget widget-schema-json-ld">
  <div class="schema-url-import">
    <label for="schema-source-url"><i class="fas fa-globe"></i> <cfif local.isEs>Generar desde una URL existente<cfelse>Generate from an existing URL</cfif></label>
    <div class="schema-url-import-controls"><input id="schema-source-url" type="url" placeholder="https://ejemplo.com"><button type="button" class="btn-social btn-upwork" id="schema-import"><i class="fas fa-search"></i> <cfif local.isEs>Analizar URL<cfelse>Analyze URL</cfif></button></div>
    <p class="tool-message" id="schema-import-message" aria-live="polite"></p>
  </div>
  <div class="schema-form-grid">
    <div><label for="schema-type"><cfif local.isEs>Tipo de Schema<cfelse>Schema type</cfif></label><select id="schema-type"><option value="Organization"><cfif local.isEs>Organización<cfelse>Organization</cfif></option><option value="Person"><cfif local.isEs>Persona<cfelse>Person</cfif></option><option value="Article"><cfif local.isEs>Artículo<cfelse>Article</cfif></option><option value="Product"><cfif local.isEs>Producto<cfelse>Product</cfif></option><option value="Service"><cfif local.isEs>Servicio<cfelse>Service</cfif></option><option value="FAQPage"><cfif local.isEs>Preguntas frecuentes (FAQ)<cfelse>FAQ page</cfif></option><option value="BreadcrumbList">Breadcrumbs</option></select></div>
    <div><label for="schema-name"><cfif local.isEs>Nombre<cfelse>Name</cfif></label><input id="schema-name" type="text" placeholder="ColdFusion Expert"></div>
    <div class="schema-field-wide"><label for="schema-url">URL</label><input id="schema-url" type="url" placeholder="https://ejemplo.com"></div>
    <div class="schema-field-wide"><label for="schema-description"><cfif local.isEs>Descripción<cfelse>Description</cfif></label><textarea id="schema-description" rows="3" placeholder='<cfif local.isEs>Descripción clara del negocio, contenido o servicio<cfelse>Clear description of the business, content, or service</cfif>'></textarea></div>
    <div class="schema-field-common"><label for="schema-image"><cfif local.isEs>URL de imagen<cfelse>Image URL</cfif></label><input id="schema-image" type="url" placeholder="https://ejemplo.com/imagen.jpg"></div>
    <div class="schema-field-common"><label for="schema-author"><cfif local.isEs>Autor<cfelse>Author</cfif></label><input id="schema-author" type="text" placeholder="Nombre del autor"></div>
    <div class="schema-field-article"><label for="schema-date"><cfif local.isEs>Fecha de publicación<cfelse>Publication date</cfif></label><input id="schema-date" type="date"></div>
    <div class="schema-field-product"><label for="schema-brand"><cfif local.isEs>Marca<cfelse>Brand</cfif></label><input id="schema-brand" type="text" placeholder="Marca"></div>
    <div class="schema-field-product schema-field-service"><label for="schema-price"><cfif local.isEs>Precio<cfelse>Price</cfif></label><input id="schema-price" type="number" min="0" step="0.01" placeholder="0.00"></div>
    <div class="schema-field-product schema-field-service"><label for="schema-currency"><cfif local.isEs>Moneda<cfelse>Currency</cfif></label><input id="schema-currency" type="text" value="ARS" maxlength="3"></div>
    <div class="schema-field-service"><label for="schema-service"><cfif local.isEs>Tipo de servicio<cfelse>Service type</cfif></label><input id="schema-service" type="text" placeholder="Consultoría ColdFusion"></div>
    <div class="schema-field-service"><label for="schema-area"><cfif local.isEs>Área de servicio<cfelse>Service area</cfif></label><input id="schema-area" type="text" placeholder="Argentina"></div>
    <div class="schema-field-faq schema-field-wide"><label for="schema-faq-question"><cfif local.isEs>Pregunta FAQ<cfelse>FAQ question</cfif></label><input id="schema-faq-question" type="text" placeholder="¿Cuál es tu pregunta?"><label for="schema-faq-answer"><cfif local.isEs>Respuesta<cfelse>Answer</cfif></label><textarea id="schema-faq-answer" rows="3" placeholder='<cfif local.isEs>Respuesta completa y útil<cfelse>Complete and helpful answer</cfif>'></textarea></div>
    <div class="schema-field-breadcrumb schema-field-wide"><label for="schema-breadcrumbs"><cfif local.isEs>Elementos del breadcrumb<cfelse>Breadcrumb items</cfif></label><textarea id="schema-breadcrumbs" rows="4" placeholder='<cfif local.isEs>Inicio | https://ejemplo.com/<br>Herramientas | https://ejemplo.com/tools<br>Mi herramienta | https://ejemplo.com/tools/mi-herramienta<cfelse>Home | https://example.com/<br>Tools | https://example.com/tools<br>My tool | https://example.com/tools/my-tool</cfif>'></textarea><small><cfif local.isEs>Un elemento por línea, separado por una barra vertical (|).<cfelse>One item per line, separated by a vertical bar (|).</cfif></small></div>
  </div>
  <div class="widget-buttons"><button type="button" class="btn-social btn-upwork" id="schema-generate"><i class="fas fa-wand-magic-sparkles"></i> <cfif local.isEs>Generar JSON-LD<cfelse>Generate JSON-LD</cfif></button><button type="button" class="tool-copy" data-copy-target="schema-output"><i class="far fa-copy"></i> <cfif local.isEs>Copiar código<cfelse>Copy code</cfif></button></div>
  <p class="tool-message" id="schema-message" aria-live="polite"></p>
  <label for="schema-output"><cfif local.isEs>Resultado listo para pegar en el HTML<cfelse>Result ready to paste into HTML</cfif></label><textarea id="schema-output" rows="16" readonly spellcheck="false"></textarea>
</div>
<script>
(function(){var type=document.getElementById('schema-type'),output=document.getElementById('schema-output'),message=document.getElementById('schema-message'),importMessage=document.getElementById('schema-import-message'),es=<cfif local.isEs>true<cfelse>false</cfif>;
var groups={Organization:'.schema-field-common',Person:'.schema-field-common',Article:'.schema-field-common,.schema-field-article',Product:'.schema-field-common,.schema-field-product',Service:'.schema-field-common,.schema-field-service',FAQPage:'.schema-field-faq',BreadcrumbList:'.schema-field-breadcrumb'};
function val(id){return document.getElementById(id).value.trim();} function put(obj,key,value){if(value)obj[key]=value;}
function setInput(id,value){if(value)document.getElementById(id).value=value;}
function update(){document.querySelectorAll('.schema-field-common,.schema-field-article,.schema-field-product,.schema-field-service,.schema-field-faq,.schema-field-breadcrumb').forEach(function(el){el.style.display='none';});groups[type.value].split(',').forEach(function(sel){document.querySelectorAll(sel).forEach(function(el){el.style.display='block';});});}
function generate(){var selected=type.value,data={'@context':'https://schema.org','@type':selected};if(selected==='FAQPage'){var q=val('schema-faq-question'),a=val('schema-faq-answer');if(!q||!a){message.textContent=es?'Completá la pregunta y la respuesta.':'Complete the question and answer.';message.className='tool-message is-error';return;}data.mainEntity=[{'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}];}else if(selected==='BreadcrumbList'){var lines=val('schema-breadcrumbs').split(/\r?\n/).filter(Boolean);if(!lines.length){message.textContent=es?'Agregá al menos un elemento.':'Add at least one item.';message.className='tool-message is-error';return;}data.itemListElement=lines.map(function(line,index){var parts=line.split('|'),item={'@type':'ListItem',position:index+1,name:(parts[0]||'').trim()};if((parts[1]||'').trim())item.item=parts[1].trim();return item;});}else{var name=val('schema-name');if(!name){message.textContent=es?'Completá el nombre.':'Enter a name.';message.className='tool-message is-error';return;}put(data,'name',name);put(data,'url',val('schema-url'));put(data,'description',val('schema-description'));put(data,'image',val('schema-image'));if(selected==='Organization'||selected==='Person'||selected==='Article')put(data,'author',val('schema-author')?{'@type':'Person',name:val('schema-author')}:null);if(selected==='Article')put(data,'datePublished',val('schema-date'));if(selected==='Product'){put(data,'brand',val('schema-brand')?{'@type':'Brand',name:val('schema-brand')}:null);if(val('schema-price'))data.offers={'@type':'Offer',price:val('schema-price'),priceCurrency:val('schema-currency')||'ARS',availability:'https://schema.org/InStock'};}if(selected==='Service'){put(data,'serviceType',val('schema-service'));put(data,'areaServed',val('schema-area'));if(val('schema-price'))data.offers={'@type':'Offer',price:val('schema-price'),priceCurrency:val('schema-currency')||'ARS'};}}output.value='<script type="application/ld+json">\n'+JSON.stringify(data,null,2)+'\n<\/script>';message.textContent=es?'JSON-LD generado correctamente.':'JSON-LD generated successfully.';message.className='tool-message';}
function importFromUrl(){var url=val('schema-source-url');if(!url){importMessage.textContent=es?'Ingresá una URL válida.':'Enter a valid URL.';importMessage.className='tool-message is-error';return;}if(!/^https?:\/\//i.test(url))url='https://'+url;setInput('schema-source-url',url);importMessage.textContent=es?'Analizando la página...':'Analyzing page...';importMessage.className='tool-message';fetch('/tools-api.cfm?method=extractMetaTags&url='+encodeURIComponent(url)).then(function(r){return r.json();}).then(function(data){if(!data.success&&!data.SUCCESS)throw new Error(data.error||data.ERROR||'fetch_failed');var d={};Object.keys(data).forEach(function(k){d[k.toLowerCase()]=data[k];});setInput('schema-name',d.title||d.ogtitle||'');setInput('schema-url',d.canonical||url);setInput('schema-description',d.description||d.ogdescription||'');setInput('schema-image',d.ogimage||'');importMessage.textContent=es?'Datos encontrados. Revisá los campos y generá el JSON-LD.':'Data found. Review the fields and generate the JSON-LD.';importMessage.className='tool-message';}).catch(function(){importMessage.textContent=es?'No se pudo leer esa URL. Puede estar caída o bloquear el acceso automático.':'That URL could not be read. It may be down or block automated access.';importMessage.className='tool-message is-error';});}
type.addEventListener('change',update);document.getElementById('schema-generate').addEventListener('click',generate);document.getElementById('schema-import').addEventListener('click',importFromUrl);update();}());
</script>
