<div class="tool-widget widget-sql-json-cfml-converter">
  <div class="sql-cfml-options"><div><label for="sql-cfml-mode"><cfif local.isEs>Tipo de conversión<cfelse>Conversion type</cfif></label><select id="sql-cfml-mode" class="sql-cfml-select"><option value="sql-json"><cfif local.isEs>SQL → JSON<cfelse>SQL → JSON</cfif></option><option value="json-struct"><cfif local.isEs>JSON → Struct CFScript<cfelse>JSON → CFScript struct</cfif></option><option value="json-query"><cfif local.isEs>JSON → Query CFML<cfelse>JSON → CFML query</cfif></option></select></div><div><label for="sql-cfml-indent"><cfif local.isEs>Indentación<cfelse>Indentation</cfif></label><select id="sql-cfml-indent" class="sql-cfml-select"><option value="4">4 espacios</option><option value="2">2 espacios</option><option value="tab">Tabulaciones</option></select></div></div>
  <div class="sql-cfml-grid"><div><label for="sql-cfml-input"><cfif local.isEs>Entrada SQL o JSON<cfelse>SQL or JSON input</cfif></label><textarea id="sql-cfml-input" rows="16" spellcheck="false" placeholder="SELECT id, nombre FROM usuarios"></textarea></div><div><label for="sql-cfml-output"><cfif local.isEs>Resultado<cfelse>Result</cfif></label><textarea id="sql-cfml-output" rows="16" readonly spellcheck="false"></textarea></div></div>
  <div class="widget-buttons"><button type="button" class="btn-social btn-upwork" id="sql-cfml-convert"><i class="fas fa-wand-magic-sparkles"></i> <cfif local.isEs>Convertir<cfelse>Convert</cfif></button><button type="button" class="tool-copy" data-copy-target="sql-cfml-output"><i class="far fa-copy"></i> <cfif local.isEs>Copiar resultado<cfelse>Copy result</cfif></button><button type="button" class="tool-copy" id="sql-cfml-clear"><i class="fas fa-eraser"></i> <cfif local.isEs>Limpiar<cfelse>Clear</cfif></button></div>
  <p class="tool-message" id="sql-cfml-message" aria-live="polite"></p>
</div>
<script>
(function(){var input=document.getElementById('sql-cfml-input'),output=document.getElementById('sql-cfml-output'),mode=document.getElementById('sql-cfml-mode'),indent=document.getElementById('sql-cfml-indent'),message=document.getElementById('sql-cfml-message'),es=<cfif local.isEs>true<cfelse>false</cfif>;
function pad(level){var unit=indent.value==='tab'?'\t':Array(Number(indent.value)+1).join(' ');return Array(level+1).join(unit);}
function quote(value){return JSON.stringify(value===undefined?null:value);}
function splitValues(text){var out=[],current='',quoteChar='',depth=0;for(var i=0;i<text.length;i++){var ch=text.charAt(i);if(quoteChar){current+=ch;if(ch===quoteChar&&text.charAt(i-1)!=='\\')quoteChar='';}else if(ch==='"'||ch==="'"){quoteChar=ch;current+=ch;}else if(ch==='('||ch==='['||ch==='{'){depth++;current+=ch;}else if(ch===')'||ch===']'||ch==='}') {depth--;current+=ch;}else if(ch===','&&depth===0){out.push(current.trim());current='';}else current+=ch;}if(current.trim()||text.trim()==='')out.push(current.trim());return out;}
function sqlValue(value){var v=value.trim();if(/^null$/i.test(v))return null;if(/^(true|false)$/i.test(v))return v.toLowerCase()==='true';if(/^-?\d+(\.\d+)?$/.test(v))return Number(v);if((v.charAt(0)==='"'&&v.charAt(v.length-1)==='"')||(v.charAt(0)==="'"&&v.charAt(v.length-1)==="'"))return v.slice(1,-1).replace(/''/g,"'");return v;}
function sqlToJson(sql){var insert=sql.match(/insert\s+into\s+([\w.]+)\s*\(([^)]+)\)\s*values\s*([\s\S]*)/i);if(insert){var columns=splitValues(insert[2]).map(function(v){return v.replace(/[\[\]`]/g,'').trim();}),rows=[],rowRegex=/\(([^()]*)\)/g,row;while((row=rowRegex.exec(insert[3]))!==null){var values=splitValues(row[1]),obj={};columns.forEach(function(col,index){obj[col]=sqlValue(values[index]);});rows.push(obj);}return JSON.stringify(rows,null,Number(indent.value)||2);}var select=sql.match(/select\s+([\s\S]+?)\s+from\s+([\w.]+)/i);if(!select)throw new Error(es?'No se reconoció un SELECT o INSERT simple.':'No simple SELECT or INSERT was recognized.');var cols=select[1].split(',').map(function(v){return v.trim().split(/\s+as\s+/i).pop().replace(/^[\w.]+\./,'').replace(/[\[\]`]/g,'');}).filter(function(v){return v&&v!=='*';});if(!cols.length)cols=['id','name'];var sample={};cols.forEach(function(col){sample[col]=null;});return JSON.stringify([sample],null,Number(indent.value)||2);}
function jsonValue(value,level){if(value===null)return 'javacast("null","")';if(typeof value==='string')return quote(value);if(typeof value==='number'||typeof value==='boolean')return String(value);if(Array.isArray(value))return '[\n'+value.map(function(item){return pad(level+1)+jsonValue(item,level+1);}).join(',\n')+'\n'+pad(level)+']';var keys=Object.keys(value);return '{\n'+keys.map(function(key){return pad(level+1)+quote(key)+': '+jsonValue(value[key],level+1);}).join(',\n')+'\n'+pad(level)+'}';}
function jsonToStruct(json){var value=JSON.parse(json);return 'var data = '+jsonValue(value,0)+';';}
function jsonToQuery(json){var value=JSON.parse(json);var rows=Array.isArray(value)?value:[value];if(!rows.length||typeof rows[0]!=='object')throw new Error(es?'El JSON debe contener objetos con columnas.':'JSON must contain objects with columns.');var columns=[];rows.forEach(function(row){Object.keys(row).forEach(function(key){if(columns.indexOf(key)<0)columns.push(key);});});var names=columns.map(quote).join(', '),types=columns.map(function(){return '"varchar"';}).join(', '),data=rows.map(function(row){return pad(1)+'{'+columns.map(function(col){return quote(col)+': '+jsonValue(row[col],1);}).join(', ')+'}';}).join(',\n');return 'var q = queryNew(['+names+'], ['+types+'], [\n'+data+'\n]);';}
function convert(){if(!input.value.trim()){output.value='';message.textContent=es?'Pegá SQL o JSON para convertir.':'Paste SQL or JSON to convert.';message.className='tool-message is-error';return;}try{var value=mode.value==='sql-json'?sqlToJson(input.value):mode.value==='json-struct'?jsonToStruct(input.value):jsonToQuery(input.value);output.value=value;message.textContent=es?'Conversión lista. Revisá tipos y nombres de columnas antes de usar el resultado.':'Conversion ready. Review column names and types before using the result.';message.className='tool-message';}catch(error){output.value='';message.textContent=error.message;message.className='tool-message is-error';}}
document.getElementById('sql-cfml-convert').addEventListener('click',convert);mode.addEventListener('change',function(){if(input.value.trim())convert();});indent.addEventListener('change',function(){if(input.value.trim())convert();});document.getElementById('sql-cfml-clear').addEventListener('click',function(){input.value='';output.value='';message.textContent='';});}());
</script>
