<div class="tool-widget widget-text-diff-checker">
  <div class="diff-options"><label><input type="checkbox" id="diff-ignore-space"> <cfif local.isEs>Ignorar espacios<cfelse>Ignore whitespace</cfif></label><label><input type="checkbox" id="diff-ignore-case"> <cfif local.isEs>Ignorar mayúsculas<cfelse>Ignore case</cfif></label></div>
  <div class="diff-input-grid"><div><label for="diff-left"><cfif local.isEs>Texto original<cfelse>Original text</cfif></label><textarea id="diff-left" rows="14" spellcheck="false" placeholder='<cfif local.isEs>Pegá acá la primera versión<cfelse>Paste the first version here</cfif>'></textarea></div><div><label for="diff-right"><cfif local.isEs>Texto nuevo<cfelse>New text</cfif></label><textarea id="diff-right" rows="14" spellcheck="false" placeholder='<cfif local.isEs>Pegá acá la segunda versión<cfelse>Paste the second version here</cfif>'></textarea></div></div>
  <div class="widget-buttons"><button type="button" class="btn-social btn-upwork" id="diff-compare"><i class="fas fa-code-compare"></i> <cfif local.isEs>Comparar textos<cfelse>Compare texts</cfif></button><button type="button" class="tool-copy" id="diff-copy"><i class="far fa-copy"></i> <cfif local.isEs>Copiar resultado<cfelse>Copy result</cfif></button></div>
  <p class="tool-message" id="diff-message" aria-live="polite"></p><div class="diff-summary" id="diff-summary"></div><div class="diff-output" id="diff-output" aria-live="polite"></div>
</div>
<script>
(function(){var left=document.getElementById('diff-left'),right=document.getElementById('diff-right'),out=document.getElementById('diff-output'),summary=document.getElementById('diff-summary'),message=document.getElementById('diff-message'),ignoreSpace=document.getElementById('diff-ignore-space'),ignoreCase=document.getElementById('diff-ignore-case'),es=<cfif local.isEs>true<cfelse>false</cfif>;
function esc(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}function key(s){if(ignoreSpace.checked)s=s.replace(/\s+/g,'');if(ignoreCase.checked)s=s.toLowerCase();return s;}
function compare(){var a=left.value.split(/\r?\n/),b=right.value.split(/\r?\n/),n=a.length,m=b.length,dp=Array(n+1);var i,j;for(i=0;i<=n;i++)dp[i]=Array(m+1).fill(0);for(i=n-1;i>=0;i--)for(j=m-1;j>=0;j--)dp[i][j]=key(a[i])===key(b[j])?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);var rows=[],x=0,y=0,added=0,removed=0,same=0;while(x<n&&y<m){if(key(a[x])===key(b[y])){rows.push({kind:'same',left:x+1,right:y+1,text:a[x]});x++;y++;same++;}else if(dp[x+1][y]>=dp[x][y+1]){rows.push({kind:'removed',left:x+1,right:'',text:a[x]});x++;removed++;}else{rows.push({kind:'added',left:'',right:y+1,text:b[y]});y++;added++;}}while(x<n){rows.push({kind:'removed',left:x+1,right:'',text:a[x++]});removed++;}while(y<m){rows.push({kind:'added',left:'',right:y+1,text:b[y++]});added++;}message.textContent=es?'Comparación terminada.':'Comparison complete.';message.className='tool-message';summary.textContent=(es?'Agregadas: ':'Added: ')+added+' · '+(es?'Eliminadas: ':'Removed: ')+removed+' · '+(es?'Sin cambios: ':'Unchanged: ')+same;out.innerHTML='<div class="diff-header"><span>'+(es?'Línea':'Line')+'</span><span>'+(es?'Resultado':'Result')+'</span></div>'+rows.map(function(row){return '<div class="diff-row '+row.kind+'"><span class="diff-line">'+(row.left||'')+' '+(row.right||'')+'</span><code>'+(row.kind==='removed'?'− ':row.kind==='added'?'+ ':'  ')+esc(row.text||'')+'</code></div>';}).join('');}
document.getElementById('diff-compare').addEventListener('click',compare);document.getElementById('diff-copy').addEventListener('click',function(){navigator.clipboard.writeText(out.innerText||'');});}());
</script>
